const palettes = [
  {
    id: "nordic-fjord",
    name: "Nordic Fjord",
    colors: ["#1e3a4c", "#2d6a6e", "#5fa88f", "#c9b896", "#f0e6d2"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "fresh"],
  },
  {
    id: "steel-blue",
    name: "Steel Blue",
    colors: ["#3d4451", "#5b6a85", "#8b9cc4", "#c3cbe0", "#eef1f8"],
    category: "Urban",
    style: "Cool",
    tags: ["calm", "elegant"],
  },
  {
    id: "sunset-drive",
    name: "Sunset Drive",
    colors: ["#4a1942", "#a3286b", "#e8546b", "#f4915c", "#f9d977"],
    category: "Warm",
    style: "Vibrant",
    tags: ["energetic", "bold"],
  },
  {
    id: "olive-grove",
    name: "Olive Grove",
    colors: ["#2b3325", "#4f5c3a", "#8a9a6b", "#c3caa8", "#eef0e0"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "cozy"],
  },
  {
    id: "monochrome",
    name: "Monochrome",
    colors: ["#111111", "#4a4a4a", "#8a8a8a", "#c7c7c7", "#ffffff"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["elegant", "bold"],
  },
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    colors: ["#0b3d3f", "#1c6b6a", "#4d9e94", "#8fc9ba", "#d8ede0"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "fresh"],
  },
  {
    id: "pastel-dream",
    name: "Pastel Dream",
    colors: ["#c9b8f0", "#f0b8d8", "#f7d9a8", "#f4f0a8", "#c8ecd0"],
    category: "Abstract",
    style: "Pastel",
    tags: ["playful", "calm"],
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    colors: ["#2b0a3d", "#9c1f8f", "#e0388a", "#4fc3e0", "#2f6fe0"],
    category: "Urban",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "earth-tones",
    name: "Earth Tones",
    colors: ["#4a2f1f", "#8a5a3a", "#c48b5a", "#b3a878", "#e6dfc4"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "calm"],
  },
  {
    id: "minimal-ui",
    name: "Minimal UI",
    colors: ["#0f0f0f", "#4a4a4a", "#8a8a8a", "#c7c7c7", "#ffffff"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["elegant", "calm"],
  },
  {
    id: "purple-haze",
    name: "Purple Haze",
    colors: ["#2e1a47", "#5b3a8a", "#8a6bc4", "#bda8e0", "#eee6f7"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["moody", "elegant"],
  },
  {
    id: "tropical",
    name: "Tropical",
    colors: ["#0f6b6e", "#2fa88a", "#7fd68f", "#f0c95a", "#f2954a"],
    category: "Nature",
    style: "Vibrant",
    tags: ["energetic", "fresh"],
  },
  {
    id: "autumn-blaze",
    name: "Autumn Blaze",
    colors: ["#5c1f0f", "#a13a1c", "#d9702e", "#e8a94a", "#f2d38a"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "bold"],
  },
  {
    id: "midnight-sky",
    name: "Midnight Sky",
    colors: ["#0a0a1f", "#1c1c3d", "#33336b", "#5c5c9e", "#9c9cd4"],
    category: "Cool",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    colors: ["#3d1a2e", "#8a3a6b", "#d97fa8", "#f2b8cf", "#fce4ec"],
    category: "Nature",
    style: "Pastel",
    tags: ["playful", "calm"],
  },
  {
    id: "desert-sand",
    name: "Desert Sand",
    colors: ["#3d2b1f", "#8a5f3a", "#c99a5c", "#e0c290", "#f5e6c8"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "calm"],
  },
  {
    id: "arctic-mint",
    name: "Arctic Mint",
    colors: ["#0f2e2b", "#1f6b5c", "#4fa88f", "#9cd6c2", "#e0f5ee"],
    category: "Cool",
    style: "Pastel",
    tags: ["fresh", "calm"],
  },
  {
    id: "royal-velvet",
    name: "Royal Velvet",
    colors: ["#1a0a2e", "#3d1c6b", "#6b3a9e", "#9c6bc4", "#d4b8ec"],
    category: "Vintage",
    style: "Dark",
    tags: ["elegant", "moody"],
  },
  {
    id: "citrus-punch",
    name: "Citrus Punch",
    colors: ["#7a4a00", "#d97a00", "#f2a900", "#f7d94a", "#f9f0a8"],
    category: "Warm",
    style: "Vibrant",
    tags: ["energetic", "playful"],
  },
  {
    id: "slate-storm",
    name: "Slate Storm",
    colors: ["#1c2530", "#33404f", "#5c6c7a", "#8a99a3", "#c7d1d8"],
    category: "Urban",
    style: "Cool",
    tags: ["moody", "elegant"],
  },
  {
    id: "coral-reef",
    name: "Coral Reef",
    colors: ["#1a3d3d", "#2f7a7a", "#4fb3a3", "#f27a5c", "#f9b98a"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "energetic"],
  },
  {
    id: "berry-fields",
    name: "Berry Fields",
    colors: ["#2e0f2e", "#6b1f5c", "#a83a7a", "#d970a8", "#f2b8d4"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "bold"],
  },
  {
    id: "forest-canopy",
    name: "Forest Canopy",
    colors: ["#0f2e1a", "#1f5c33", "#3d8a5c", "#7ab38a", "#c7e0c2"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "fresh"],
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    colors: ["#3d1f0a", "#8a4a1f", "#d9822e", "#f2b95c", "#fce4a8"],
    category: "Warm",
    style: "Vintage",
    tags: ["cozy", "elegant"],
  },
  {
    id: "neon-nights",
    name: "Neon Nights",
    colors: ["#0a0014", "#3d0a5c", "#8a1fb3", "#e02fd4", "#f26bf2"],
    category: "Urban",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "sage-whisper",
    name: "Sage Whisper",
    colors: ["#2b3320", "#5c6b45", "#8fa370", "#c2cfa8", "#eaf0dc"],
    category: "Nature",
    style: "Pastel",
    tags: ["calm", "fresh"],
  },
  {
    id: "blush-clay",
    name: "Blush Clay",
    colors: ["#4a2b26", "#8a5147", "#c48a7a", "#e0b8a8", "#f7e4dc"],
    category: "Vintage",
    style: "Earthy",
    tags: ["cozy", "elegant"],
  },
  {
    id: "electric-lime",
    name: "Electric Lime",
    colors: ["#0a1f00", "#3d6b00", "#7ab300", "#c2e000", "#eeff5c"],
    category: "Abstract",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "smoky-quartz",
    name: "Smoky Quartz",
    colors: ["#1f1a1c", "#4a3d40", "#7a6b70", "#ab9ea3", "#dcd4d7"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["moody", "elegant"],
  },
  {
    id: "cobalt-wave",
    name: "Cobalt Wave",
    colors: ["#001a4a", "#003d8a", "#1f6bcf", "#5ca3f2", "#a8d4fc"],
    category: "Cool",
    style: "Vibrant",
    tags: ["fresh", "bold"],
  },
  {
    id: "terracotta-sun",
    name: "Terracotta Sun",
    colors: ["#3d1a0f", "#8a3a1f", "#c46b3a", "#e0a26b", "#f7d9b8"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "bold"],
  },
  {
    id: "orchid-mist",
    name: "Orchid Mist",
    colors: ["#2e0a2e", "#6b1f6b", "#a83aa3", "#d97ad4", "#f2c2f0"],
    category: "Abstract",
    style: "Pastel",
    tags: ["playful", "elegant"],
  },
  {
    id: "glacier-blue",
    name: "Glacier Blue",
    colors: ["#0a2633", "#1f4d5c", "#3d7a8a", "#7ab3c2", "#c2e4ec"],
    category: "Cool",
    style: "Pastel",
    tags: ["calm", "fresh"],
  },
  {
    id: "wine-cellar",
    name: "Wine Cellar",
    colors: ["#260a14", "#5c1426", "#8a2640", "#b34d63", "#dc99a3"],
    category: "Vintage",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "honey-comb",
    name: "Honey Comb",
    colors: ["#3d2900", "#8a5c00", "#d99500", "#f2c24a", "#fce49c"],
    category: "Warm",
    style: "Vibrant",
    tags: ["cozy", "energetic"],
  },
  {
    id: "moss-stone",
    name: "Moss Stone",
    colors: ["#1a2614", "#3d4d2b", "#5c7a45", "#8fa36b", "#c7d4a8"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "cozy"],
  },
  {
    id: "twilight-plum",
    name: "Twilight Plum",
    colors: ["#1a0a26", "#3d1a4d", "#6b337a", "#9c5ca3", "#cf9ec9"],
    category: "Cool",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "aqua-frost",
    name: "Aqua Frost",
    colors: ["#00262b", "#00595c", "#1f9ca3", "#5cd4d1", "#b3f2ec"],
    category: "Cool",
    style: "Vibrant",
    tags: ["fresh", "calm"],
  },
];

export default palettes;
