// Combined palette library
// 38 original palettes + 379 newly generated palettes = 417 total
const palettes = [
  {
    id: "nordic-fjord",
    name: "Nordic Fjord",
    colors: ["#1e3a4c", "#2d6a6e", "#5fa88f", "#c9b896", "#f0e6d2"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "fresh"],
  },
  {
    id: "steel-blue",
    name: "Steel Blue",
    colors: ["#3d4451", "#5b6a85", "#8b9cc4", "#c3cbe0", "#eef1f8"],
    category: "Urban",
    style: "Cool",
    tags: ["calm", "elegant"],
  },
  {
    id: "sunset-drive",
    name: "Sunset Drive",
    colors: ["#4a1942", "#a3286b", "#e8546b", "#f4915c", "#f9d977"],
    category: "Warm",
    style: "Vibrant",
    tags: ["energetic", "bold"],
  },
  {
    id: "olive-grove",
    name: "Olive Grove",
    colors: ["#2b3325", "#4f5c3a", "#8a9a6b", "#c3caa8", "#eef0e0"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "cozy"],
  },
  {
    id: "monochrome",
    name: "Monochrome",
    colors: ["#111111", "#4a4a4a", "#8a8a8a", "#c7c7c7", "#ffffff"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["elegant", "bold"],
  },
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    colors: ["#0b3d3f", "#1c6b6a", "#4d9e94", "#8fc9ba", "#d8ede0"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "fresh"],
  },
  {
    id: "pastel-dream",
    name: "Pastel Dream",
    colors: ["#c9b8f0", "#f0b8d8", "#f7d9a8", "#f4f0a8", "#c8ecd0"],
    category: "Abstract",
    style: "Pastel",
    tags: ["playful", "calm"],
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    colors: ["#2b0a3d", "#9c1f8f", "#e0388a", "#4fc3e0", "#2f6fe0"],
    category: "Urban",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "earth-tones",
    name: "Earth Tones",
    colors: ["#4a2f1f", "#8a5a3a", "#c48b5a", "#b3a878", "#e6dfc4"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "calm"],
  },
  {
    id: "minimal-ui",
    name: "Minimal UI",
    colors: ["#0f0f0f", "#4a4a4a", "#8a8a8a", "#c7c7c7", "#ffffff"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["elegant", "calm"],
  },
  {
    id: "purple-haze",
    name: "Purple Haze",
    colors: ["#2e1a47", "#5b3a8a", "#8a6bc4", "#bda8e0", "#eee6f7"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["moody", "elegant"],
  },
  {
    id: "tropical",
    name: "Tropical",
    colors: ["#0f6b6e", "#2fa88a", "#7fd68f", "#f0c95a", "#f2954a"],
    category: "Nature",
    style: "Vibrant",
    tags: ["energetic", "fresh"],
  },
  {
    id: "autumn-blaze",
    name: "Autumn Blaze",
    colors: ["#5c1f0f", "#a13a1c", "#d9702e", "#e8a94a", "#f2d38a"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "bold"],
  },
  {
    id: "midnight-sky",
    name: "Midnight Sky",
    colors: ["#0a0a1f", "#1c1c3d", "#33336b", "#5c5c9e", "#9c9cd4"],
    category: "Cool",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    colors: ["#3d1a2e", "#8a3a6b", "#d97fa8", "#f2b8cf", "#fce4ec"],
    category: "Nature",
    style: "Pastel",
    tags: ["playful", "calm"],
  },
  {
    id: "desert-sand",
    name: "Desert Sand",
    colors: ["#3d2b1f", "#8a5f3a", "#c99a5c", "#e0c290", "#f5e6c8"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "calm"],
  },
  {
    id: "arctic-mint",
    name: "Arctic Mint",
    colors: ["#0f2e2b", "#1f6b5c", "#4fa88f", "#9cd6c2", "#e0f5ee"],
    category: "Cool",
    style: "Pastel",
    tags: ["fresh", "calm"],
  },
  {
    id: "royal-velvet",
    name: "Royal Velvet",
    colors: ["#1a0a2e", "#3d1c6b", "#6b3a9e", "#9c6bc4", "#d4b8ec"],
    category: "Vintage",
    style: "Dark",
    tags: ["elegant", "moody"],
  },
  {
    id: "citrus-punch",
    name: "Citrus Punch",
    colors: ["#7a4a00", "#d97a00", "#f2a900", "#f7d94a", "#f9f0a8"],
    category: "Warm",
    style: "Vibrant",
    tags: ["energetic", "playful"],
  },
  {
    id: "slate-storm",
    name: "Slate Storm",
    colors: ["#1c2530", "#33404f", "#5c6c7a", "#8a99a3", "#c7d1d8"],
    category: "Urban",
    style: "Cool",
    tags: ["moody", "elegant"],
  },
  {
    id: "coral-reef",
    name: "Coral Reef",
    colors: ["#1a3d3d", "#2f7a7a", "#4fb3a3", "#f27a5c", "#f9b98a"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "energetic"],
  },
  {
    id: "berry-fields",
    name: "Berry Fields",
    colors: ["#2e0f2e", "#6b1f5c", "#a83a7a", "#d970a8", "#f2b8d4"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "bold"],
  },
  {
    id: "forest-canopy",
    name: "Forest Canopy",
    colors: ["#0f2e1a", "#1f5c33", "#3d8a5c", "#7ab38a", "#c7e0c2"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "fresh"],
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    colors: ["#3d1f0a", "#8a4a1f", "#d9822e", "#f2b95c", "#fce4a8"],
    category: "Warm",
    style: "Vintage",
    tags: ["cozy", "elegant"],
  },
  {
    id: "neon-nights",
    name: "Neon Nights",
    colors: ["#0a0014", "#3d0a5c", "#8a1fb3", "#e02fd4", "#f26bf2"],
    category: "Urban",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "sage-whisper",
    name: "Sage Whisper",
    colors: ["#2b3320", "#5c6b45", "#8fa370", "#c2cfa8", "#eaf0dc"],
    category: "Nature",
    style: "Pastel",
    tags: ["calm", "fresh"],
  },
  {
    id: "blush-clay",
    name: "Blush Clay",
    colors: ["#4a2b26", "#8a5147", "#c48a7a", "#e0b8a8", "#f7e4dc"],
    category: "Vintage",
    style: "Earthy",
    tags: ["cozy", "elegant"],
  },
  {
    id: "electric-lime",
    name: "Electric Lime",
    colors: ["#0a1f00", "#3d6b00", "#7ab300", "#c2e000", "#eeff5c"],
    category: "Abstract",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "smoky-quartz",
    name: "Smoky Quartz",
    colors: ["#1f1a1c", "#4a3d40", "#7a6b70", "#ab9ea3", "#dcd4d7"],
    category: "Abstract",
    style: "Monochrome",
    tags: ["moody", "elegant"],
  },
  {
    id: "cobalt-wave",
    name: "Cobalt Wave",
    colors: ["#001a4a", "#003d8a", "#1f6bcf", "#5ca3f2", "#a8d4fc"],
    category: "Cool",
    style: "Vibrant",
    tags: ["fresh", "bold"],
  },
  {
    id: "terracotta-sun",
    name: "Terracotta Sun",
    colors: ["#3d1a0f", "#8a3a1f", "#c46b3a", "#e0a26b", "#f7d9b8"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "bold"],
  },
  {
    id: "orchid-mist",
    name: "Orchid Mist",
    colors: ["#2e0a2e", "#6b1f6b", "#a83aa3", "#d97ad4", "#f2c2f0"],
    category: "Abstract",
    style: "Pastel",
    tags: ["playful", "elegant"],
  },
  {
    id: "glacier-blue",
    name: "Glacier Blue",
    colors: ["#0a2633", "#1f4d5c", "#3d7a8a", "#7ab3c2", "#c2e4ec"],
    category: "Cool",
    style: "Pastel",
    tags: ["calm", "fresh"],
  },
  {
    id: "wine-cellar",
    name: "Wine Cellar",
    colors: ["#260a14", "#5c1426", "#8a2640", "#b34d63", "#dc99a3"],
    category: "Vintage",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "honey-comb",
    name: "Honey Comb",
    colors: ["#3d2900", "#8a5c00", "#d99500", "#f2c24a", "#fce49c"],
    category: "Warm",
    style: "Vibrant",
    tags: ["cozy", "energetic"],
  },
  {
    id: "moss-stone",
    name: "Moss Stone",
    colors: ["#1a2614", "#3d4d2b", "#5c7a45", "#8fa36b", "#c7d4a8"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "cozy"],
  },
  {
    id: "twilight-plum",
    name: "Twilight Plum",
    colors: ["#1a0a26", "#3d1a4d", "#6b337a", "#9c5ca3", "#cf9ec9"],
    category: "Cool",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "aqua-frost",
    name: "Aqua Frost",
    colors: ["#00262b", "#00595c", "#1f9ca3", "#5cd4d1", "#b3f2ec"],
    category: "Cool",
    style: "Vibrant",
    tags: ["fresh", "calm"],
  },
  {
    id: "honey-bay",
    name: "Honey Bay",
    colors: ["#22190c", "#5d4621", "#bb8e43", "#8faad7", "#dce4f2"],
    category: "Nature",
    style: "Dark",
    tags: ["bold", "serene"],
  },
  {
    id: "meadow-echo",
    name: "Meadow Echo",
    colors: ["#272c14", "#4f6d2d", "#59a43c", "#9dd59b", "#e1f1e5"],
    category: "Urban",
    style: "Earthy",
    tags: ["elegant", "fresh"],
  },
  {
    id: "honey-dawn",
    name: "Honey Dawn",
    colors: ["#3c2f0c", "#7d611a", "#cb9d2a", "#90a9e7", "#d0dbf5"],
    category: "Abstract",
    style: "Cool",
    tags: ["bold", "fresh"],
  },
  {
    id: "jade-bloom",
    name: "Jade Bloom",
    colors: ["#084320", "#11783b", "#22d069", "#89e9b0", "#c9f4da"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["fresh", "energetic"],
  },
  {
    id: "iris-echo",
    name: "Iris Echo",
    colors: ["#0d0b3f", "#291782", "#5423c5", "#a16de4", "#e4cdf5"],
    category: "Abstract",
    style: "Earthy",
    tags: ["elegant", "bold"],
  },
  {
    id: "violet-drift",
    name: "Violet Drift",
    colors: ["#10112e", "#292362", "#5d41b6", "#b29ada", "#e3d6f0"],
    category: "Abstract",
    style: "Earthy",
    tags: ["moody", "fresh"],
  },
  {
    id: "mustard-drift",
    name: "Mustard Drift",
    colors: ["#2a1d0d", "#74611e", "#c3c82a", "#c1dd7d", "#e5f3d9"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "lagoon-glow",
    name: "Lagoon Glow",
    colors: ["#192d26", "#33635f", "#58a2af", "#a1bcce", "#dee3ec"],
    category: "Vintage",
    style: "Dark",
    tags: ["cozy", "vibrant"],
  },
  {
    id: "horizon-dream",
    name: "Horizon Dream",
    colors: ["#0a1b32", "#173967", "#2f6dbf", "#96b7e2", "#e1eaf6"],
    category: "Abstract",
    style: "Earthy",
    tags: ["fresh", "serene"],
  },
  {
    id: "rosewood-shore",
    name: "Rosewood Shore",
    colors: ["#420c3b", "#6c1454", "#ce278a", "#e782b0", "#f9e4eb"],
    category: "Vintage",
    style: "Earthy",
    tags: ["cozy", "playful"],
  },
  {
    id: "magenta-frost",
    name: "Magenta Frost",
    colors: ["#200e27", "#61276b", "#a93eaa", "#d286c9", "#eccce4"],
    category: "Nature",
    style: "Earthy",
    tags: ["calm", "elegant"],
  },
  {
    id: "forest-veil",
    name: "Forest Veil",
    colors: ["#121f0e", "#2f7130", "#43b462", "#92d1b3", "#e4f2ef"],
    category: "Nature",
    style: "Earthy",
    tags: ["fresh", "playful"],
  },
  {
    id: "cosmos-bloom",
    name: "Cosmos Bloom",
    colors: ["#0c0d44", "#151668", "#2b2dc4", "#7e7fdf", "#e2e2f7"],
    category: "Abstract",
    style: "Earthy",
    tags: ["moody", "energetic"],
  },
  {
    id: "seafoam-storm",
    name: "Seafoam Storm",
    colors: ["#103b34", "#207062", "#35ad97", "#9bded2", "#e3f5f2"],
    category: "Urban",
    style: "Earthy",
    tags: ["playful", "moody"],
  },
  {
    id: "sapphire-haze",
    name: "Sapphire Haze",
    colors: ["#12243e", "#1e3266", "#3b4fc4", "#8788db", "#d8d5f2"],
    category: "Urban",
    style: "Warm",
    tags: ["bold", "cozy"],
  },
  {
    id: "salmon-echo",
    name: "Salmon Echo",
    colors: ["#25050e", "#7c1631", "#cc2854", "#e68da5", "#f2cad5"],
    category: "Urban",
    style: "Vibrant",
    tags: ["fresh", "serene"],
  },
  {
    id: "gold-dawn",
    name: "Gold Dawn",
    colors: ["#221707", "#675116", "#cdb82d", "#e3e383", "#eff4cf"],
    category: "Urban",
    style: "Cool",
    tags: ["cozy", "playful"],
  },
  {
    id: "lake-grove",
    name: "Lake Grove",
    colors: ["#15292c", "#2f5961", "#4c8c97", "#9bc3cb", "#ddeaed"],
    category: "Warm",
    style: "Dark",
    tags: ["fresh", "bold"],
  },
  {
    id: "moss-canyon",
    name: "Moss Canyon",
    colors: ["#32430d", "#5c7b19", "#8bba26", "#a88be6", "#dacdf4"],
    category: "Warm",
    style: "Earthy",
    tags: ["fresh", "serene"],
  },
  {
    id: "teal-harbor",
    name: "Teal Harbor",
    colors: ["#122a30", "#245460", "#429bb1", "#d9a79b", "#f4e7e4"],
    category: "Cool",
    style: "Dark",
    tags: ["cozy", "calm"],
  },
  {
    id: "citrus-veil",
    name: "Citrus Veil",
    colors: ["#292a10", "#696c2b", "#adb046", "#8886ce", "#e8e7f5"],
    category: "Abstract",
    style: "Earthy",
    tags: ["calm", "elegant"],
  },
  {
    id: "citrus-bloom",
    name: "Citrus Bloom",
    colors: ["#413a07", "#8d7e0f", "#e6cd1f", "#6a7aee", "#c7cdf8"],
    category: "Abstract",
    style: "Dark",
    tags: ["playful", "energetic"],
  },
  {
    id: "olive-ember",
    name: "Olive Ember",
    colors: ["#293815", "#516d2c", "#7ea947", "#b9d299", "#ebf2e2"],
    category: "Vintage",
    style: "Earthy",
    tags: ["fresh", "playful"],
  },
  {
    id: "spruce-dawn",
    name: "Spruce Dawn",
    colors: ["#1d3415", "#297429", "#37b256", "#93d8b5", "#d7efe9"],
    category: "Warm",
    style: "Vibrant",
    tags: ["elegant", "vibrant"],
  },
  {
    id: "blush-echo",
    name: "Blush Echo",
    colors: ["#38172f", "#5a274b", "#b25597", "#cb90ba", "#e9d1e2"],
    category: "Cool",
    style: "Cool",
    tags: ["serene", "vibrant"],
  },
  {
    id: "flamingo-dawn",
    name: "Flamingo Dawn",
    colors: ["#220612", "#861946", "#cb2a6d", "#e489af", "#f6dee8"],
    category: "Cool",
    style: "Cool",
    tags: ["fresh", "elegant"],
  },
  {
    id: "marigold-bay",
    name: "Marigold Bay",
    colors: ["#362e0d", "#6c5d1a", "#caad32", "#8697e1", "#ccd3f2"],
    category: "Vintage",
    style: "Warm",
    tags: ["energetic", "cozy"],
  },
  {
    id: "rose-dream",
    name: "Rose Dream",
    colors: ["#320e19", "#742030", "#be343c", "#dd8c85", "#f1d5cd"],
    category: "Vintage",
    style: "Earthy",
    tags: ["fresh", "cozy"],
  },
  {
    id: "spruce-mist",
    name: "Spruce Mist",
    colors: ["#052909", "#0f6c26", "#27e06d", "#7cecb6", "#dbfaef"],
    category: "Vintage",
    style: "Neon",
    tags: ["playful", "moody"],
  },
  {
    id: "lemon-shore",
    name: "Lemon Shore",
    colors: ["#414407", "#868c12", "#d5dd22", "#e2e672", "#f7f8de"],
    category: "Nature",
    style: "Vibrant",
    tags: ["vibrant", "bold"],
  },
  {
    id: "mustard-mist",
    name: "Mustard Mist",
    colors: ["#414606", "#7c860c", "#d6e716", "#7d73f1", "#dfdcfb"],
    category: "Vintage",
    style: "Neon",
    tags: ["moody", "serene"],
  },
  {
    id: "jungle-wave",
    name: "Jungle Wave",
    colors: ["#0c2717", "#19644a", "#27c4b5", "#7dcfde", "#d2e4f1"],
    category: "Urban",
    style: "Earthy",
    tags: ["bold", "playful"],
  },
  {
    id: "meadow-trail",
    name: "Meadow Trail",
    colors: ["#282a11", "#4a5b21", "#7ac240", "#9ad48b", "#e2f3e3"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["playful", "moody"],
  },
  {
    id: "aqua-glow",
    name: "Aqua Glow",
    colors: ["#11342b", "#227877", "#35abcf", "#87b3dd", "#d1d9ef"],
    category: "Warm",
    style: "Warm",
    tags: ["playful", "energetic"],
  },
  {
    id: "rosewood-echo",
    name: "Rosewood Echo",
    colors: ["#291033", "#601a63", "#c72aa6", "#e291bd", "#efced8"],
    category: "Urban",
    style: "Cool",
    tags: ["moody", "elegant"],
  },
  {
    id: "mint-valley",
    name: "Mint Valley",
    colors: ["#0d1e14", "#235745", "#40b5aa", "#a0d0d9", "#d7e4ed"],
    category: "Nature",
    style: "Vibrant",
    tags: ["bold", "serene"],
  },
  {
    id: "lemon-grove",
    name: "Lemon Grove",
    colors: ["#311d0e", "#6a5019", "#d5c827", "#d3e38c", "#e1f0cd"],
    category: "Urban",
    style: "Vibrant",
    tags: ["cozy", "fresh"],
  },
  {
    id: "punch-dawn",
    name: "Punch Dawn",
    colors: ["#32132b", "#5d1f40", "#c33960", "#d99093", "#ecd4ce"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["calm", "elegant"],
  },
  {
    id: "cerulean-valley",
    name: "Cerulean Valley",
    colors: ["#121f27", "#2d4d60", "#4d82a4", "#cba993", "#f3ece7"],
    category: "Cool",
    style: "Earthy",
    tags: ["energetic", "vibrant"],
  },
  {
    id: "rosewood-whisper",
    name: "Rosewood Whisper",
    colors: ["#301333", "#64205a", "#c83a8e", "#dc95ae", "#eccdd0"],
    category: "Cool",
    style: "Earthy",
    tags: ["serene", "playful"],
  },
  {
    id: "grape-bay",
    name: "Grape Bay",
    colors: ["#1b0b2c", "#4c1b69", "#9a2fbb", "#d788e0", "#f7e2f7"],
    category: "Nature",
    style: "Earthy",
    tags: ["bold", "playful"],
  },
  {
    id: "forest-wave",
    name: "Forest Wave",
    colors: ["#0d1e0b", "#206529", "#33bd68", "#83d7b8", "#def3f0"],
    category: "Cool",
    style: "Cool",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "twilight-drift",
    name: "Twilight Drift",
    colors: ["#1b1233", "#352463", "#6444ba", "#c9db9c", "#edf3df"],
    category: "Warm",
    style: "Warm",
    tags: ["serene", "vibrant"],
  },
  {
    id: "meadow-peak",
    name: "Meadow Peak",
    colors: ["#121d0b", "#406728", "#6aa941", "#c29ed9", "#e9dbf1"],
    category: "Vintage",
    style: "Earthy",
    tags: ["moody", "fresh"],
  },
  {
    id: "teal-mist",
    name: "Teal Mist",
    colors: ["#17382d", "#23615b", "#40aec2", "#83b1d2", "#ced8ea"],
    category: "Urban",
    style: "Vibrant",
    tags: ["energetic", "cozy"],
  },
  {
    id: "honey-storm",
    name: "Honey Storm",
    colors: ["#371b11", "#68431b", "#cba52a", "#dddf83", "#eaf2d6"],
    category: "Warm",
    style: "Warm",
    tags: ["serene", "calm"],
  },
  {
    id: "meadow-dawn",
    name: "Meadow Dawn",
    colors: ["#15220d", "#395824", "#679c43", "#abce94", "#e5f0de"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "moody"],
  },
  {
    id: "spruce-drift",
    name: "Spruce Drift",
    colors: ["#0d3114", "#20743a", "#3cc87b", "#91e0bf", "#c9f0e4"],
    category: "Abstract",
    style: "Cool",
    tags: ["serene", "cozy"],
  },
  {
    id: "violet-dawn",
    name: "Violet Dawn",
    colors: ["#0a0f32", "#20127b", "#5c14cf", "#ba69e8", "#f1d2f5"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "bold"],
  },
  {
    id: "fern-harbor",
    name: "Fern Harbor",
    colors: ["#0d3525", "#217e64", "#30b7a3", "#88dfde", "#daf2f5"],
    category: "Cool",
    style: "Vibrant",
    tags: ["elegant", "playful"],
  },
  {
    id: "marigold-frost",
    name: "Marigold Frost",
    colors: ["#2f2a0d", "#746721", "#bba635", "#909cdf", "#c8ceef"],
    category: "Warm",
    style: "Dark",
    tags: ["elegant", "fresh"],
  },
  {
    id: "crimson-whisper",
    name: "Crimson Whisper",
    colors: ["#230d17", "#662230", "#c63e38", "#daa590", "#f3ebe1"],
    category: "Warm",
    style: "Earthy",
    tags: ["moody", "serene"],
  },
  {
    id: "lavender-whisper",
    name: "Lavender Whisper",
    colors: ["#180924", "#4d1b66", "#a634c4", "#da8ee0", "#f1cbee"],
    category: "Cool",
    style: "Dark",
    tags: ["elegant", "vibrant"],
  },
  {
    id: "lagoon-veil",
    name: "Lagoon Veil",
    colors: ["#0b2f25", "#157976", "#19a9d4", "#85bae9", "#d1dbf4"],
    category: "Vintage",
    style: "Neon",
    tags: ["bold", "playful"],
  },
  {
    id: "rust-shore",
    name: "Rust Shore",
    colors: ["#39101c", "#70191d", "#d64825", "#e5b48c", "#f8f2e6"],
    category: "Urban",
    style: "Vibrant",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "marigold-harbor",
    name: "Marigold Harbor",
    colors: ["#1e1410", "#684f35", "#af9a57", "#c4c58e", "#edf0e5"],
    category: "Vintage",
    style: "Warm",
    tags: ["fresh", "elegant"],
  },
  {
    id: "orchid-haze",
    name: "Orchid Haze",
    colors: ["#220829", "#641b7a", "#9c2ebe", "#c67cdc", "#e7caf0"],
    category: "Cool",
    style: "Vibrant",
    tags: ["energetic", "cozy"],
  },
  {
    id: "marine-mist",
    name: "Marine Mist",
    colors: ["#0d1f2c", "#1f4865", "#3883b8", "#dcaf8f", "#efdcce"],
    category: "Abstract",
    style: "Warm",
    tags: ["bold", "moody"],
  },
  {
    id: "twilight-shore",
    name: "Twilight Shore",
    colors: ["#0c0e1c", "#342c6e", "#7347be", "#bd96d5", "#e7d2ea"],
    category: "Abstract",
    style: "Cool",
    tags: ["cozy", "playful"],
  },
  {
    id: "teal-peak",
    name: "Teal Peak",
    colors: ["#082419", "#147565", "#1ac4d4", "#75c0e6", "#dce7f6"],
    category: "Vintage",
    style: "Dark",
    tags: ["playful", "cozy"],
  },
  {
    id: "rust-grove",
    name: "Rust Grove",
    colors: ["#3e0f15", "#822317", "#ce5b1b", "#e9c388", "#f2edcc"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["energetic", "fresh"],
  },
  {
    id: "amethyst-canyon",
    name: "Amethyst Canyon",
    colors: ["#0c0626", "#271373", "#4a24da", "#cee770", "#ebf5c6"],
    category: "Abstract",
    style: "Cool",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "grape-whisper",
    name: "Grape Whisper",
    colors: ["#26072f", "#5a116d", "#b72adc", "#87e76e", "#e8fae3"],
    category: "Abstract",
    style: "Warm",
    tags: ["elegant", "fresh"],
  },
  {
    id: "fern-valley",
    name: "Fern Valley",
    colors: ["#14321e", "#226248", "#37b8a3", "#91d2d8", "#d6e6ee"],
    category: "Nature",
    style: "Warm",
    tags: ["serene", "vibrant"],
  },
  {
    id: "spruce-shore",
    name: "Spruce Shore",
    colors: ["#0d2b09", "#13771f", "#16cf5b", "#8aecc7", "#cef4ef"],
    category: "Urban",
    style: "Neon",
    tags: ["vibrant", "energetic"],
  },
  {
    id: "horizon-shore",
    name: "Horizon Shore",
    colors: ["#113335", "#21627d", "#2c76ce", "#90a1e1", "#dddbf3"],
    category: "Nature",
    style: "Cool",
    tags: ["elegant", "bold"],
  },
  {
    id: "emerald-harbor",
    name: "Emerald Harbor",
    colors: ["#043318", "#0f8f46", "#1bde6f", "#69e9a0", "#cbf6dd"],
    category: "Nature",
    style: "Vibrant",
    tags: ["bold", "calm"],
  },
  {
    id: "jade-glow",
    name: "Jade Glow",
    colors: ["#16311b", "#285a38", "#47a171", "#9fd4bf", "#d6ede7"],
    category: "Abstract",
    style: "Dark",
    tags: ["calm", "cozy"],
  },
  {
    id: "mauve-frost",
    name: "Mauve Frost",
    colors: ["#351635", "#592652", "#a7478e", "#d49bbe", "#f0dde6"],
    category: "Warm",
    style: "Dark",
    tags: ["calm", "energetic"],
  },
  {
    id: "marigold-echo",
    name: "Marigold Echo",
    colors: ["#28170f", "#6f4e23", "#bfa533", "#d1d782", "#ebf2dd"],
    category: "Cool",
    style: "Cool",
    tags: ["calm", "serene"],
  },
  {
    id: "midnight-shore",
    name: "Midnight Shore",
    colors: ["#0c1b2e", "#1c3182", "#2b22ca", "#9676e0", "#dfcbf0"],
    category: "Cool",
    style: "Cool",
    tags: ["serene", "vibrant"],
  },
  {
    id: "berry-veil",
    name: "Berry Veil",
    colors: ["#270526", "#80147d", "#d82bd3", "#e581e2", "#f8e1f7"],
    category: "Cool",
    style: "Earthy",
    tags: ["elegant", "moody"],
  },
  {
    id: "honey-peak",
    name: "Honey Peak",
    colors: ["#2f2308", "#6c5114", "#d7a42e", "#6f92e3", "#dfe7f9"],
    category: "Nature",
    style: "Dark",
    tags: ["elegant", "energetic"],
  },
  {
    id: "peony-glow",
    name: "Peony Glow",
    colors: ["#3b102c", "#7b255d", "#b63a8b", "#dc99c5", "#eccbe1"],
    category: "Warm",
    style: "Cool",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "plum-canyon",
    name: "Plum Canyon",
    colors: ["#220f30", "#451f5f", "#803caf", "#b486d3", "#e6d8f0"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["cozy", "calm"],
  },
  {
    id: "aqua-veil",
    name: "Aqua Veil",
    colors: ["#182c33", "#2f5462", "#4d8ba2", "#c89e8d", "#f0e4e0"],
    category: "Vintage",
    style: "Dark",
    tags: ["vibrant", "bold"],
  },
  {
    id: "iris-dawn",
    name: "Iris Dawn",
    colors: ["#150d28", "#3f2779", "#623dbb", "#c8dd97", "#e5eece"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["fresh", "cozy"],
  },
  {
    id: "indigo-whisper",
    name: "Indigo Whisper",
    colors: ["#0d1823", "#23356b", "#3435b9", "#9580d4", "#e9dff2"],
    category: "Nature",
    style: "Cool",
    tags: ["bold", "playful"],
  },
  {
    id: "basil-dream",
    name: "Basil Dream",
    colors: ["#2c3e09", "#457411", "#5fc61e", "#96ea7a", "#d5f7d0"],
    category: "Abstract",
    style: "Dark",
    tags: ["bold", "vibrant"],
  },
  {
    id: "denim-bloom",
    name: "Denim Bloom",
    colors: ["#0c122e", "#1c2661", "#384bb4", "#8995d8", "#d6daf0"],
    category: "Nature",
    style: "Cool",
    tags: ["playful", "calm"],
  },
  {
    id: "violet-frost",
    name: "Violet Frost",
    colors: ["#231634", "#3e285c", "#744bad", "#b7d095", "#e5eed8"],
    category: "Urban",
    style: "Cool",
    tags: ["elegant", "energetic"],
  },
  {
    id: "honey-bloom",
    name: "Honey Bloom",
    colors: ["#311b05", "#895b0e", "#e6b51b", "#f1e480", "#f7f8c7"],
    category: "Urban",
    style: "Dark",
    tags: ["energetic", "serene"],
  },
  {
    id: "lavender-canyon",
    name: "Lavender Canyon",
    colors: ["#17113b", "#411c78", "#9e2fd9", "#d77de0", "#f7e6f5"],
    category: "Nature",
    style: "Warm",
    tags: ["moody", "serene"],
  },
  {
    id: "coral-shore",
    name: "Coral Shore",
    colors: ["#2c0e1c", "#5c203b", "#bb467b", "#d083a6", "#f4e5ec"],
    category: "Cool",
    style: "Warm",
    tags: ["serene", "vibrant"],
  },
  {
    id: "salmon-wave",
    name: "Salmon Wave",
    colors: ["#320a16", "#851c3a", "#c82a58", "#8be6cb", "#e0f8f1"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["energetic", "calm"],
  },
  {
    id: "iris-grove",
    name: "Iris Grove",
    colors: ["#1a123b", "#382069", "#7b3cc3", "#bd8fdc", "#e4c9ee"],
    category: "Nature",
    style: "Cool",
    tags: ["elegant", "fresh"],
  },
  {
    id: "fern-glow",
    name: "Fern Glow",
    colors: ["#0f3024", "#1e6151", "#39b4a7", "#99dcde", "#def1f4"],
    category: "Warm",
    style: "Vibrant",
    tags: ["vibrant", "playful"],
  },
  {
    id: "mauve-trail",
    name: "Mauve Trail",
    colors: ["#400c2a", "#7a1951", "#ca2e88", "#dd78b3", "#f1cce1"],
    category: "Vintage",
    style: "Earthy",
    tags: ["moody", "calm"],
  },
  {
    id: "spruce-grove",
    name: "Spruce Grove",
    colors: ["#093e22", "#12713e", "#20ca6e", "#ec8bc0", "#f9dcec"],
    category: "Warm",
    style: "Earthy",
    tags: ["serene", "moody"],
  },
  {
    id: "denim-dream",
    name: "Denim Dream",
    colors: ["#0c313d", "#134d87", "#1342d2", "#7070ea", "#e0d9f7"],
    category: "Vintage",
    style: "Neon",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "sage-dream",
    name: "Sage Dream",
    colors: ["#272705", "#7b8c12", "#ace120", "#c4ee85", "#edfbe1"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["elegant", "bold"],
  },
  {
    id: "azure-dream",
    name: "Azure Dream",
    colors: ["#062a44", "#0d5387", "#198fe7", "#efa166", "#f9ddc8"],
    category: "Vintage",
    style: "Neon",
    tags: ["moody", "serene"],
  },
  {
    id: "crimson-drift",
    name: "Crimson Drift",
    colors: ["#390d1b", "#741b2c", "#b92a34", "#e0827b", "#f3d6ce"],
    category: "Cool",
    style: "Dark",
    tags: ["serene", "moody"],
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    colors: ["#280a35", "#5e1b7c", "#922dbe", "#bc75db", "#e8d2f2"],
    category: "Vintage",
    style: "Earthy",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "fuchsia-haze",
    name: "Fuchsia Haze",
    colors: ["#2e0d2d", "#712370", "#c246c0", "#d486d3", "#eccbeb"],
    category: "Urban",
    style: "Cool",
    tags: ["fresh", "elegant"],
  },
  {
    id: "azure-storm",
    name: "Azure Storm",
    colors: ["#082f3c", "#13608f", "#1c77d7", "#6c99eb", "#c4cff7"],
    category: "Nature",
    style: "Vibrant",
    tags: ["cozy", "bold"],
  },
  {
    id: "rust-trail",
    name: "Rust Trail",
    colors: ["#41190f", "#742d1c", "#bc4a2e", "#8cd1e3", "#cbeaf2"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["elegant", "cozy"],
  },
  {
    id: "cosmos-valley",
    name: "Cosmos Valley",
    colors: ["#0a182e", "#16278b", "#2d18db", "#a27be9", "#f0e3f8"],
    category: "Vintage",
    style: "Neon",
    tags: ["playful", "fresh"],
  },
  {
    id: "fern-dusk",
    name: "Fern Dusk",
    colors: ["#1e2510", "#4b5e28", "#88a948", "#ae9ad3", "#dad1eb"],
    category: "Nature",
    style: "Warm",
    tags: ["elegant", "playful"],
  },
  {
    id: "clay-trail",
    name: "Clay Trail",
    colors: ["#341520", "#6e272f", "#c55342", "#d3a283", "#f1eadd"],
    category: "Urban",
    style: "Vibrant",
    tags: ["fresh", "bold"],
  },
  {
    id: "cobalt-whisper",
    name: "Cobalt Whisper",
    colors: ["#0b1138", "#1d2b83", "#2f42c0", "#8e99e1", "#d9ddf4"],
    category: "Warm",
    style: "Warm",
    tags: ["cozy", "bold"],
  },
  {
    id: "olive-shore",
    name: "Olive Shore",
    colors: ["#252008", "#7b8415", "#a0e418", "#a2e870", "#ddf6d8"],
    category: "Urban",
    style: "Vibrant",
    tags: ["fresh", "energetic"],
  },
  {
    id: "fern-frost",
    name: "Fern Frost",
    colors: ["#3e3a0b", "#778e13", "#90ec1c", "#a0ed7e", "#ddf8db"],
    category: "Warm",
    style: "Vibrant",
    tags: ["energetic", "serene"],
  },
  {
    id: "forest-echo",
    name: "Forest Echo",
    colors: ["#072c06", "#127c1c", "#1ed047", "#7ceba4", "#d1f8e4"],
    category: "Abstract",
    style: "Earthy",
    tags: ["fresh", "serene"],
  },
  {
    id: "orchid-drift",
    name: "Orchid Drift",
    colors: ["#0d0823", "#481988", "#9e1ddc", "#de7ce6", "#f6dbf1"],
    category: "Urban",
    style: "Neon",
    tags: ["playful", "vibrant"],
  },
  {
    id: "fuchsia-dusk",
    name: "Fuchsia Dusk",
    colors: ["#2c1638", "#51255e", "#ae4eb8", "#d392d1", "#edd4e9"],
    category: "Urban",
    style: "Dark",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "lake-dusk",
    name: "Lake Dusk",
    colors: ["#092026", "#216c7e", "#339ab3", "#8ecddc", "#dff0f4"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "calm"],
  },
  {
    id: "meadow-bloom",
    name: "Meadow Bloom",
    colors: ["#1a2009", "#507e20", "#54cc2a", "#8ae189", "#d1f1d9"],
    category: "Warm",
    style: "Warm",
    tags: ["moody", "fresh"],
  },
  {
    id: "violet-harbor",
    name: "Violet Harbor",
    colors: ["#14192c", "#2b285f", "#6945b8", "#ba9ad4", "#f0e6f3"],
    category: "Warm",
    style: "Earthy",
    tags: ["vibrant", "serene"],
  },
  {
    id: "grape-valley",
    name: "Grape Valley",
    colors: ["#150d27", "#401c5e", "#af39cd", "#db89d7", "#f6e7f2"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "cozy"],
  },
  {
    id: "orchid-echo",
    name: "Orchid Echo",
    colors: ["#220633", "#5c148a", "#9224d9", "#c287e8", "#e6d0f5"],
    category: "Warm",
    style: "Neon",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "berry-frost",
    name: "Berry Frost",
    colors: ["#39073a", "#801181", "#c81bca", "#6bea69", "#cef8cd"],
    category: "Urban",
    style: "Vibrant",
    tags: ["bold", "vibrant"],
  },
  {
    id: "clay-frost",
    name: "Clay Frost",
    colors: ["#3e0a11", "#7a1515", "#c43621", "#eaa38a", "#f5d9c6"],
    category: "Urban",
    style: "Cool",
    tags: ["playful", "cozy"],
  },
  {
    id: "fuchsia-cove",
    name: "Fuchsia Cove",
    colors: ["#200820", "#6b1c6b", "#b52fb4", "#82de83", "#d0f2d0"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["moody", "cozy"],
  },
  {
    id: "clay-veil",
    name: "Clay Veil",
    colors: ["#380d0d", "#7c2a1d", "#c1562e", "#e3b08e", "#f3e1cd"],
    category: "Urban",
    style: "Vibrant",
    tags: ["calm", "moody"],
  },
  {
    id: "wheat-frost",
    name: "Wheat Frost",
    colors: ["#382c10", "#7c6e23", "#c7c43c", "#d6df8f", "#e6efc9"],
    category: "Urban",
    style: "Dark",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "sapphire-canyon",
    name: "Sapphire Canyon",
    colors: ["#0d2131", "#1e4272", "#3460c7", "#919fe2", "#dcddf5"],
    category: "Abstract",
    style: "Cool",
    tags: ["moody", "bold"],
  },
  {
    id: "mauve-echo",
    name: "Mauve Echo",
    colors: ["#3c092e", "#821363", "#d420a1", "#79ea99", "#d4f8de"],
    category: "Warm",
    style: "Cool",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "cerulean-glow",
    name: "Cerulean Glow",
    colors: ["#0d1e27", "#264c71", "#3c68b2", "#8a9dd7", "#d1d4ef"],
    category: "Abstract",
    style: "Earthy",
    tags: ["cozy", "vibrant"],
  },
  {
    id: "gold-veil",
    name: "Gold Veil",
    colors: ["#322212", "#695226", "#b89e42", "#d1ca81", "#eff0d6"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["energetic", "calm"],
  },
  {
    id: "lavender-storm",
    name: "Lavender Storm",
    colors: ["#170424", "#520f82", "#8118cc", "#b3f087", "#ddf8c9"],
    category: "Urban",
    style: "Vibrant",
    tags: ["vibrant", "moody"],
  },
  {
    id: "honey-echo",
    name: "Honey Echo",
    colors: ["#351710", "#623a18", "#c79726", "#dfda7d", "#f0f4dd"],
    category: "Cool",
    style: "Warm",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "gold-glow",
    name: "Gold Glow",
    colors: ["#2f1d0d", "#7b5823", "#c4a038", "#dbcf82", "#eff0cb"],
    category: "Warm",
    style: "Cool",
    tags: ["serene", "bold"],
  },
  {
    id: "punch-glow",
    name: "Punch Glow",
    colors: ["#26081d", "#6f1849", "#c82c70", "#e07595", "#f3cbd2"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["moody", "calm"],
  },
  {
    id: "magenta-bay",
    name: "Magenta Bay",
    colors: ["#360c37", "#6a1a6c", "#af2fb2", "#d87fdb", "#edc8ee"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "elegant"],
  },
  {
    id: "brick-echo",
    name: "Brick Echo",
    colors: ["#371704", "#79340c", "#ce5b19", "#e99a6c", "#f8e4d8"],
    category: "Warm",
    style: "Vibrant",
    tags: ["playful", "moody"],
  },
  {
    id: "caramel-bay",
    name: "Caramel Bay",
    colors: ["#2e1308", "#6c3914", "#ce8327", "#e6c57f", "#f8f3dc"],
    category: "Nature",
    style: "Vibrant",
    tags: ["cozy", "moody"],
  },
  {
    id: "cobalt-valley",
    name: "Cobalt Valley",
    colors: ["#091525", "#1b3166", "#3951ca", "#8e91e1", "#cbc7f0"],
    category: "Urban",
    style: "Vibrant",
    tags: ["bold", "fresh"],
  },
  {
    id: "clay-mist",
    name: "Clay Mist",
    colors: ["#1f0f0b", "#663526", "#b15e45", "#d5a799", "#f3e6e3"],
    category: "Warm",
    style: "Dark",
    tags: ["bold", "elegant"],
  },
  {
    id: "lake-wave",
    name: "Lake Wave",
    colors: ["#0b2828", "#206670", "#379cc1", "#8fbfdf", "#ccddf0"],
    category: "Nature",
    style: "Warm",
    tags: ["elegant", "playful"],
  },
  {
    id: "navy-echo",
    name: "Navy Echo",
    colors: ["#101137", "#20226c", "#3d41c5", "#d9d783", "#f5f4de"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["playful", "serene"],
  },
  {
    id: "jade-ember",
    name: "Jade Ember",
    colors: ["#0c411a", "#198335", "#25be4e", "#e786cd", "#f4c9e9"],
    category: "Nature",
    style: "Vibrant",
    tags: ["bold", "vibrant"],
  },
  {
    id: "pine-mist",
    name: "Pine Mist",
    colors: ["#1c3a13", "#306220", "#55ae39", "#ca93db", "#efe0f4"],
    category: "Vintage",
    style: "Earthy",
    tags: ["serene", "bold"],
  },
  {
    id: "peony-trail",
    name: "Peony Trail",
    colors: ["#300e26", "#691f54", "#b53690", "#89dba1", "#d7f3df"],
    category: "Vintage",
    style: "Dark",
    tags: ["moody", "elegant"],
  },
  {
    id: "tide-bay",
    name: "Tide Bay",
    colors: ["#052223", "#146a7c", "#229ed5", "#83bcea", "#cbdef6"],
    category: "Cool",
    style: "Earthy",
    tags: ["serene", "bold"],
  },
  {
    id: "ocean-dream",
    name: "Ocean Dream",
    colors: ["#0b372d", "#117a7c", "#13a0d3", "#83b6ed", "#c9d3f4"],
    category: "Urban",
    style: "Vibrant",
    tags: ["vibrant", "calm"],
  },
  {
    id: "brick-whisper",
    name: "Brick Whisper",
    colors: ["#2c161a", "#562a26", "#a36143", "#cbb18d", "#edeadb"],
    category: "Vintage",
    style: "Dark",
    tags: ["serene", "moody"],
  },
  {
    id: "ruby-mist",
    name: "Ruby Mist",
    colors: ["#28161f", "#582d37", "#af5958", "#c49b8c", "#f1ebe6"],
    category: "Nature",
    style: "Earthy",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "sapphire-wave",
    name: "Sapphire Wave",
    colors: ["#0e181a", "#2a4256", "#4c66a8", "#9698cb", "#e7e5f1"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["calm", "bold"],
  },
  {
    id: "punch-dream",
    name: "Punch Dream",
    colors: ["#3e0619", "#770e32", "#d71e5d", "#ea80a4", "#f5c8d7"],
    category: "Urban",
    style: "Neon",
    tags: ["serene", "energetic"],
  },
  {
    id: "teal-veil",
    name: "Teal Veil",
    colors: ["#0d3d34", "#1b7a75", "#2dbdc9", "#7ecde2", "#ddeef7"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["elegant", "calm"],
  },
  {
    id: "spruce-veil",
    name: "Spruce Veil",
    colors: ["#0b361d", "#197942", "#33d477", "#e37ab6", "#f7d9ea"],
    category: "Cool",
    style: "Warm",
    tags: ["bold", "elegant"],
  },
  {
    id: "fern-drift",
    name: "Fern Drift",
    colors: ["#2b2816", "#616832", "#8ab04c", "#a2c88b", "#d6e8d4"],
    category: "Vintage",
    style: "Earthy",
    tags: ["playful", "elegant"],
  },
  {
    id: "amber-valley",
    name: "Amber Valley",
    colors: ["#381e0f", "#63351b", "#b36030", "#84bcdd", "#d8eaf4"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "elegant"],
  },
  {
    id: "marine-canyon",
    name: "Marine Canyon",
    colors: ["#0e1e2a", "#20435c", "#498abb", "#9cbed8", "#e8f0f5"],
    category: "Vintage",
    style: "Earthy",
    tags: ["playful", "energetic"],
  },
  {
    id: "aqua-drift",
    name: "Aqua Drift",
    colors: ["#122824", "#2b605e", "#4b9ea8", "#89baca", "#d4e3ec"],
    category: "Abstract",
    style: "Warm",
    tags: ["serene", "bold"],
  },
  {
    id: "wheat-harbor",
    name: "Wheat Harbor",
    colors: ["#2e1f13", "#715b29", "#b4ad39", "#c5d48a", "#ecf3e4"],
    category: "Warm",
    style: "Earthy",
    tags: ["elegant", "bold"],
  },
  {
    id: "moss-dawn",
    name: "Moss Dawn",
    colors: ["#243311", "#4a6a23", "#81b93e", "#a984d5", "#e1d5f0"],
    category: "Warm",
    style: "Warm",
    tags: ["fresh", "bold"],
  },
  {
    id: "rosewood-dawn",
    name: "Rosewood Dawn",
    colors: ["#1f0828", "#811486", "#e819bd", "#e86aaf", "#f8e0e7"],
    category: "Urban",
    style: "Vibrant",
    tags: ["cozy", "bold"],
  },
  {
    id: "lemon-mist",
    name: "Lemon Mist",
    colors: ["#352a1c", "#5f562e", "#a1a649", "#bccd98", "#edf3e8"],
    category: "Warm",
    style: "Vibrant",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "sky-shore",
    name: "Sky Shore",
    colors: ["#0c2536", "#1d5277", "#3c90cb", "#82b7db", "#e1edf5"],
    category: "Nature",
    style: "Dark",
    tags: ["cozy", "bold"],
  },
  {
    id: "horizon-storm",
    name: "Horizon Storm",
    colors: ["#091b1f", "#1e4a60", "#397cb7", "#98b4de", "#ccd5ef"],
    category: "Warm",
    style: "Earthy",
    tags: ["cozy", "elegant"],
  },
  {
    id: "fuchsia-frost",
    name: "Fuchsia Frost",
    colors: ["#23172e", "#522d5f", "#9e449e", "#c88ab8", "#f0e3e9"],
    category: "Warm",
    style: "Dark",
    tags: ["fresh", "energetic"],
  },
  {
    id: "sage-peak",
    name: "Sage Peak",
    colors: ["#2f410e", "#4e6b18", "#8fc42c", "#9c77e0", "#e4daf6"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["serene", "bold"],
  },
  {
    id: "midnight-dawn",
    name: "Midnight Dawn",
    colors: ["#131d33", "#2a3570", "#3e41a4", "#8b84d0", "#e8e4f5"],
    category: "Urban",
    style: "Cool",
    tags: ["moody", "fresh"],
  },
  {
    id: "plum-harbor",
    name: "Plum Harbor",
    colors: ["#280b36", "#591978", "#9229c4", "#a9e68c", "#e2f6d8"],
    category: "Abstract",
    style: "Cool",
    tags: ["serene", "fresh"],
  },
  {
    id: "saffron-glow",
    name: "Saffron Glow",
    colors: ["#312813", "#665229", "#aa8a47", "#cbb68a", "#ede6d8"],
    category: "Abstract",
    style: "Earthy",
    tags: ["energetic", "moody"],
  },
  {
    id: "sage-ember",
    name: "Sage Ember",
    colors: ["#3a3111", "#7d8020", "#9cca29", "#a8dd7b", "#daf1d4"],
    category: "Cool",
    style: "Warm",
    tags: ["moody", "playful"],
  },
  {
    id: "olive-canyon",
    name: "Olive Canyon",
    colors: ["#232b06", "#566a11", "#a1c523", "#cce378", "#f2f7de"],
    category: "Abstract",
    style: "Warm",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "rosewood-trail",
    name: "Rosewood Trail",
    colors: ["#3a0d27", "#7c1d54", "#c42d85", "#79dfa4", "#d3f4e1"],
    category: "Warm",
    style: "Earthy",
    tags: ["calm", "moody"],
  },
  {
    id: "copper-haze",
    name: "Copper Haze",
    colors: ["#2b1806", "#844b16", "#d07927", "#e3ad7b", "#f7e9dc"],
    category: "Abstract",
    style: "Earthy",
    tags: ["energetic", "bold"],
  },
  {
    id: "flamingo-dusk",
    name: "Flamingo Dusk",
    colors: ["#270813", "#851c43", "#c22962", "#83e4c0", "#e4f9f1"],
    category: "Urban",
    style: "Vibrant",
    tags: ["playful", "calm"],
  },
  {
    id: "wheat-dream",
    name: "Wheat Dream",
    colors: ["#332c12", "#736d29", "#b5bc43", "#cbd893", "#e9f1d9"],
    category: "Vintage",
    style: "Cool",
    tags: ["playful", "serene"],
  },
  {
    id: "amber-bay",
    name: "Amber Bay",
    colors: ["#41240b", "#774315", "#cf7524", "#7fb6e8", "#e0edf9"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["moody", "elegant"],
  },
  {
    id: "cobalt-dusk",
    name: "Cobalt Dusk",
    colors: ["#0b2a31", "#154a72", "#1c56cf", "#7f87e7", "#d0c9f2"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["calm", "serene"],
  },
  {
    id: "twilight-dream",
    name: "Twilight Dream",
    colors: ["#080a20", "#29227e", "#4d31b6", "#a88cdf", "#dccbf0"],
    category: "Warm",
    style: "Earthy",
    tags: ["fresh", "elegant"],
  },
  {
    id: "sky-peak",
    name: "Sky Peak",
    colors: ["#14262d", "#2f5168", "#4f7baf", "#93a6ce", "#d0d5e9"],
    category: "Urban",
    style: "Dark",
    tags: ["moody", "fresh"],
  },
  {
    id: "sky-veil",
    name: "Sky Veil",
    colors: ["#102b39", "#245179", "#396fc1", "#8ea3dd", "#cacfef"],
    category: "Cool",
    style: "Earthy",
    tags: ["elegant", "bold"],
  },
  {
    id: "twilight-wave",
    name: "Twilight Wave",
    colors: ["#140429", "#380e70", "#7121dc", "#a777e7", "#e1d1f6"],
    category: "Warm",
    style: "Neon",
    tags: ["fresh", "bold"],
  },
  {
    id: "ruby-ember",
    name: "Ruby Ember",
    colors: ["#2f1411", "#5e2923", "#ae4b41", "#94d0d6", "#e2f2f4"],
    category: "Cool",
    style: "Earthy",
    tags: ["playful", "fresh"],
  },
  {
    id: "amber-canyon",
    name: "Amber Canyon",
    colors: ["#482706", "#73400c", "#e38320", "#ecb47b", "#f7e3ce"],
    category: "Nature",
    style: "Vibrant",
    tags: ["calm", "fresh"],
  },
  {
    id: "meadow-frost",
    name: "Meadow Frost",
    colors: ["#1a3405", "#3e780d", "#76df1e", "#b3eb83", "#e2f6d0"],
    category: "Warm",
    style: "Neon",
    tags: ["fresh", "cozy"],
  },
  {
    id: "pine-drift",
    name: "Pine Drift",
    colors: ["#1b2d0a", "#3b771c", "#53ce33", "#8fe389", "#c7f1c9"],
    category: "Nature",
    style: "Earthy",
    tags: ["bold", "fresh"],
  },
  {
    id: "amethyst-trail",
    name: "Amethyst Trail",
    colors: ["#1e1135", "#422771", "#643da8", "#ad96d7", "#e7e0f2"],
    category: "Abstract",
    style: "Cool",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "mustard-haze",
    name: "Mustard Haze",
    colors: ["#242706", "#808816", "#c0cc21", "#8079e8", "#d6d4f7"],
    category: "Cool",
    style: "Vibrant",
    tags: ["moody", "vibrant"],
  },
  {
    id: "grape-trail",
    name: "Grape Trail",
    colors: ["#190b27", "#481d61", "#9e39be", "#d590dd", "#f0cfef"],
    category: "Nature",
    style: "Vibrant",
    tags: ["bold", "calm"],
  },
  {
    id: "cobalt-peak",
    name: "Cobalt Peak",
    colors: ["#061f44", "#0d2d83", "#1d39e8", "#7d7df1", "#d3cdf9"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["elegant", "cozy"],
  },
  {
    id: "horizon-whisper",
    name: "Horizon Whisper",
    colors: ["#142834", "#2e5873", "#518db5", "#88b0ca", "#dae6ee"],
    category: "Warm",
    style: "Cool",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "azure-mist",
    name: "Azure Mist",
    colors: ["#071c2b", "#134c76", "#2b92dc", "#ecb58c", "#f9e8dc"],
    category: "Urban",
    style: "Earthy",
    tags: ["calm", "playful"],
  },
  {
    id: "peony-wave",
    name: "Peony Wave",
    colors: ["#25031b", "#850f63", "#e121a9", "#eb82cc", "#f4c5e7"],
    category: "Cool",
    style: "Neon",
    tags: ["moody", "calm"],
  },
  {
    id: "mint-veil",
    name: "Mint Veil",
    colors: ["#06371c", "#0f8756", "#18d7a2", "#86f1e2", "#c1f8f7"],
    category: "Urban",
    style: "Dark",
    tags: ["playful", "fresh"],
  },
  {
    id: "citrus-drift",
    name: "Citrus Drift",
    colors: ["#454108", "#7a730f", "#e2d51f", "#7079ed", "#d0d2f9"],
    category: "Urban",
    style: "Neon",
    tags: ["serene", "fresh"],
  },
  {
    id: "moss-harbor",
    name: "Moss Harbor",
    colors: ["#25300d", "#607d24", "#8bb434", "#9e82db", "#dacff1"],
    category: "Urban",
    style: "Dark",
    tags: ["cozy", "calm"],
  },
  {
    id: "honey-whisper",
    name: "Honey Whisper",
    colors: ["#1e160c", "#6c592d", "#a49444", "#cecb8a", "#eceed8"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["serene", "cozy"],
  },
  {
    id: "caramel-whisper",
    name: "Caramel Whisper",
    colors: ["#23080a", "#832b19", "#e07121", "#e3be71", "#f8f6e4"],
    category: "Abstract",
    style: "Dark",
    tags: ["playful", "serene"],
  },
  {
    id: "steel-haze",
    name: "Steel Haze",
    colors: ["#12253b", "#1f3766", "#3953b9", "#7f85d7", "#dddbf4"],
    category: "Cool",
    style: "Cool",
    tags: ["playful", "vibrant"],
  },
  {
    id: "caramel-trail",
    name: "Caramel Trail",
    colors: ["#34150e", "#783c22", "#b66d33", "#e1c297", "#f4ecd8"],
    category: "Cool",
    style: "Dark",
    tags: ["elegant", "moody"],
  },
  {
    id: "salmon-drift",
    name: "Salmon Drift",
    colors: ["#1d0c1a", "#69294e", "#a73a5e", "#d79a9f", "#ecd9d5"],
    category: "Abstract",
    style: "Warm",
    tags: ["elegant", "bold"],
  },
  {
    id: "jade-peak",
    name: "Jade Peak",
    colors: ["#0e3b1e", "#1d7b40", "#31ce6c", "#e592c6", "#f5d8ea"],
    category: "Warm",
    style: "Warm",
    tags: ["energetic", "serene"],
  },
  {
    id: "tide-haze",
    name: "Tide Haze",
    colors: ["#041725", "#0e5588", "#1f94e7", "#f0a977", "#fae3d3"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["cozy", "energetic"],
  },
  {
    id: "copper-drift",
    name: "Copper Drift",
    colors: ["#291513", "#5c372b", "#a9724f", "#d2b99f", "#ece5d7"],
    category: "Nature",
    style: "Cool",
    tags: ["calm", "energetic"],
  },
  {
    id: "fuchsia-wave",
    name: "Fuchsia Wave",
    colors: ["#3c1238", "#692162", "#aa39a0", "#d488cd", "#edcfea"],
    category: "Vintage",
    style: "Warm",
    tags: ["moody", "elegant"],
  },
  {
    id: "rosewood-valley",
    name: "Rosewood Valley",
    colors: ["#2f1123", "#5e2247", "#ad3f83", "#94d7ae", "#ceedda"],
    category: "Abstract",
    style: "Warm",
    tags: ["calm", "energetic"],
  },
  {
    id: "emerald-canyon",
    name: "Emerald Canyon",
    colors: ["#042a12", "#10883c", "#1ccd5e", "#8becaf", "#c8f5d8"],
    category: "Vintage",
    style: "Neon",
    tags: ["elegant", "moody"],
  },
  {
    id: "orchid-bay",
    name: "Orchid Bay",
    colors: ["#150c1f", "#552c70", "#8f43a9", "#c88cd1", "#f5e7f5"],
    category: "Urban",
    style: "Dark",
    tags: ["playful", "energetic"],
  },
  {
    id: "bronze-dawn",
    name: "Bronze Dawn",
    colors: ["#2d0c0e", "#792e1b", "#d47525", "#e2c57f", "#efeec8"],
    category: "Cool",
    style: "Earthy",
    tags: ["vibrant", "serene"],
  },
  {
    id: "lagoon-bloom",
    name: "Lagoon Bloom",
    colors: ["#14292c", "#32646a", "#4b929b", "#95c4ca", "#dbeaec"],
    category: "Urban",
    style: "Warm",
    tags: ["fresh", "calm"],
  },
  {
    id: "lagoon-shore",
    name: "Lagoon Shore",
    colors: ["#0a2b24", "#157175", "#1ba1d8", "#82b1e8", "#c8d0f2"],
    category: "Warm",
    style: "Neon",
    tags: ["playful", "elegant"],
  },
  {
    id: "rust-echo",
    name: "Rust Echo",
    colors: ["#331720", "#68292d", "#aa503b", "#d5b297", "#eae2d0"],
    category: "Abstract",
    style: "Warm",
    tags: ["bold", "vibrant"],
  },
  {
    id: "fuchsia-storm",
    name: "Fuchsia Storm",
    colors: ["#180c26", "#541c69", "#c12bc4", "#e192cf", "#edcadc"],
    category: "Nature",
    style: "Earthy",
    tags: ["moody", "energetic"],
  },
  {
    id: "pine-bay",
    name: "Pine Bay",
    colors: ["#2b2d17", "#49582a", "#7ab24f", "#98c88e", "#e0eee1"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "vibrant"],
  },
  {
    id: "ocean-peak",
    name: "Ocean Peak",
    colors: ["#072220", "#146e82", "#178ae0", "#84a5eb", "#c7cbf3"],
    category: "Abstract",
    style: "Dark",
    tags: ["serene", "fresh"],
  },
  {
    id: "gold-haze",
    name: "Gold Haze",
    colors: ["#2e2705", "#85700f", "#ddbb1a", "#758aee", "#c5cef8"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "elegant"],
  },
  {
    id: "grape-harbor",
    name: "Grape Harbor",
    colors: ["#2c1732", "#502b5b", "#8d4ba0", "#a2cd96", "#e5f1e1"],
    category: "Urban",
    style: "Dark",
    tags: ["energetic", "cozy"],
  },
  {
    id: "seafoam-glow",
    name: "Seafoam Glow",
    colors: ["#0d2321", "#2c6f68", "#4bb3a8", "#9bd3cd", "#e6f3f2"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "vibrant"],
  },
  {
    id: "berry-dusk",
    name: "Berry Dusk",
    colors: ["#361533", "#5c2557", "#9f4395", "#ca87c3", "#e9cfe6"],
    category: "Warm",
    style: "Earthy",
    tags: ["elegant", "moody"],
  },
  {
    id: "rust-mist",
    name: "Rust Mist",
    colors: ["#3b070d", "#851310", "#d1371a", "#ed9773", "#f7d7c0"],
    category: "Cool",
    style: "Neon",
    tags: ["energetic", "serene"],
  },
  {
    id: "mint-whisper",
    name: "Mint Whisper",
    colors: ["#0a3b34", "#137265", "#2adac2", "#ea8896", "#f7d2d7"],
    category: "Vintage",
    style: "Cool",
    tags: ["vibrant", "playful"],
  },
  {
    id: "fuchsia-glow",
    name: "Fuchsia Glow",
    colors: ["#350c2f", "#6d1861", "#cd2eb8", "#81e28e", "#cff4d4"],
    category: "Warm",
    style: "Cool",
    tags: ["cozy", "serene"],
  },
  {
    id: "berry-cove",
    name: "Berry Cove",
    colors: ["#40093c", "#7e1477", "#d526c8", "#e685df", "#f7dcf5"],
    category: "Warm",
    style: "Vibrant",
    tags: ["playful", "serene"],
  },
  {
    id: "clay-drift",
    name: "Clay Drift",
    colors: ["#351010", "#722e23", "#be5f3b", "#daaa89", "#f7efe5"],
    category: "Urban",
    style: "Cool",
    tags: ["vibrant", "energetic"],
  },
  {
    id: "lavender-trail",
    name: "Lavender Trail",
    colors: ["#220936", "#571688", "#8f2bdb", "#b4eb89", "#e6f8d8"],
    category: "Vintage",
    style: "Earthy",
    tags: ["cozy", "playful"],
  },
  {
    id: "fern-veil",
    name: "Fern Veil",
    colors: ["#0b3018", "#17855a", "#1bdcc0", "#8ce0ea", "#c7e2f2"],
    category: "Vintage",
    style: "Neon",
    tags: ["playful", "vibrant"],
  },
  {
    id: "terracotta-harbor",
    name: "Terracotta Harbor",
    colors: ["#220f0e", "#623428", "#af6c47", "#d7b99e", "#efe7d9"],
    category: "Nature",
    style: "Earthy",
    tags: ["moody", "elegant"],
  },
  {
    id: "brick-ember",
    name: "Brick Ember",
    colors: ["#341713", "#6a2f27", "#a74b3e", "#98d0d8", "#e2f2f4"],
    category: "Cool",
    style: "Dark",
    tags: ["playful", "serene"],
  },
  {
    id: "denim-grove",
    name: "Denim Grove",
    colors: ["#0b3044", "#165188", "#246ada", "#7c97e9", "#c2c8f4"],
    category: "Vintage",
    style: "Dark",
    tags: ["bold", "serene"],
  },
  {
    id: "clay-valley",
    name: "Clay Valley",
    colors: ["#1f130e", "#5f3b2c", "#9a624b", "#c8a292", "#f0e6e2"],
    category: "Warm",
    style: "Vibrant",
    tags: ["playful", "fresh"],
  },
  {
    id: "citrus-haze",
    name: "Citrus Haze",
    colors: ["#34340d", "#6a681b", "#c7c439", "#dbd989", "#f3f3db"],
    category: "Warm",
    style: "Earthy",
    tags: ["playful", "cozy"],
  },
  {
    id: "blush-cove",
    name: "Blush Cove",
    colors: ["#330930", "#6f145d", "#be228a", "#e56fae", "#f4c6d8"],
    category: "Urban",
    style: "Warm",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "honey-drift",
    name: "Honey Drift",
    colors: ["#3f2c11", "#69531c", "#b2a02f", "#e1e090", "#f4f7e2"],
    category: "Vintage",
    style: "Cool",
    tags: ["elegant", "playful"],
  },
  {
    id: "iris-bloom",
    name: "Iris Bloom",
    colors: ["#0d152e", "#1c1a71", "#5a2bd8", "#ae77df", "#e8cbf0"],
    category: "Nature",
    style: "Earthy",
    tags: ["playful", "moody"],
  },
  {
    id: "denim-whisper",
    name: "Denim Whisper",
    colors: ["#081244", "#122685", "#2847dc", "#7c8fe7", "#d4daf6"],
    category: "Nature",
    style: "Vibrant",
    tags: ["fresh", "cozy"],
  },
  {
    id: "fuchsia-bay",
    name: "Fuchsia Bay",
    colors: ["#33053e", "#760a7d", "#e113d3", "#f379da", "#f9c0e6"],
    category: "Cool",
    style: "Neon",
    tags: ["elegant", "playful"],
  },
  {
    id: "emerald-dream",
    name: "Emerald Dream",
    colors: ["#152f0b", "#1c8319", "#1ed446", "#71e3a7", "#d6f4ec"],
    category: "Cool",
    style: "Neon",
    tags: ["playful", "calm"],
  },
  {
    id: "teal-drift",
    name: "Teal Drift",
    colors: ["#093131", "#156572", "#2ba8d6", "#89c2e8", "#e0ebf9"],
    category: "Vintage",
    style: "Warm",
    tags: ["elegant", "moody"],
  },
  {
    id: "forest-valley",
    name: "Forest Valley",
    colors: ["#094615", "#0f7624", "#1cd842", "#ed7fd7", "#f6c1ec"],
    category: "Vintage",
    style: "Neon",
    tags: ["playful", "fresh"],
  },
  {
    id: "clover-ember",
    name: "Clover Ember",
    colors: ["#303217", "#4a5b26", "#6ead40", "#a4d59a", "#cfe8d1"],
    category: "Cool",
    style: "Vibrant",
    tags: ["moody", "vibrant"],
  },
  {
    id: "wine-dawn",
    name: "Wine Dawn",
    colors: ["#2f0b0a", "#751d1d", "#ca3c3b", "#df9190", "#f6e4e4"],
    category: "Vintage",
    style: "Earthy",
    tags: ["energetic", "fresh"],
  },
  {
    id: "reef-wave",
    name: "Reef Wave",
    colors: ["#122f2a", "#256a71", "#338ab6", "#88a9d7", "#d5d9ef"],
    category: "Urban",
    style: "Earthy",
    tags: ["playful", "vibrant"],
  },
  {
    id: "blush-trail",
    name: "Blush Trail",
    colors: ["#30122b", "#61244f", "#ac417e", "#d695b1", "#f6e8ec"],
    category: "Abstract",
    style: "Earthy",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "blush-storm",
    name: "Blush Storm",
    colors: ["#34113b", "#741b6d", "#d72c9f", "#e180a9", "#efc8ce"],
    category: "Cool",
    style: "Dark",
    tags: ["energetic", "calm"],
  },
  {
    id: "jungle-cove",
    name: "Jungle Cove",
    colors: ["#053f2a", "#0a765d", "#11d0bd", "#7ceff3", "#c4f1fa"],
    category: "Cool",
    style: "Vibrant",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "mauve-mist",
    name: "Mauve Mist",
    colors: ["#24061b", "#751457", "#cc2499", "#87e9a5", "#daf8e3"],
    category: "Nature",
    style: "Vibrant",
    tags: ["cozy", "bold"],
  },
  {
    id: "cerulean-bay",
    name: "Cerulean Bay",
    colors: ["#0a3345", "#114974", "#1e68c9", "#80a0eb", "#c7cff6"],
    category: "Cool",
    style: "Vibrant",
    tags: ["calm", "playful"],
  },
  {
    id: "fern-dream",
    name: "Fern Dream",
    colors: ["#132822", "#336c5d", "#499883", "#d3a3b0", "#efdfe3"],
    category: "Cool",
    style: "Cool",
    tags: ["serene", "vibrant"],
  },
  {
    id: "marine-valley",
    name: "Marine Valley",
    colors: ["#0e373a", "#195767", "#3093c6", "#80b3e0", "#d0def3"],
    category: "Warm",
    style: "Cool",
    tags: ["elegant", "cozy"],
  },
  {
    id: "berry-canyon",
    name: "Berry Canyon",
    colors: ["#261026", "#5b285c", "#ab4eac", "#d3a2d3", "#ead5ea"],
    category: "Warm",
    style: "Dark",
    tags: ["playful", "fresh"],
  },
  {
    id: "blush-bloom",
    name: "Blush Bloom",
    colors: ["#43072b", "#7a0f50", "#de2294", "#e879bd", "#f4c4e1"],
    category: "Warm",
    style: "Neon",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "blush-shore",
    name: "Blush Shore",
    colors: ["#301226", "#5e244a", "#b3498e", "#d59dc2", "#ebd3e3"],
    category: "Vintage",
    style: "Warm",
    tags: ["fresh", "energetic"],
  },
  {
    id: "tide-dawn",
    name: "Tide Dawn",
    colors: ["#162c32", "#2e5762", "#5094a7", "#91bcc8", "#d6e6ea"],
    category: "Cool",
    style: "Warm",
    tags: ["elegant", "calm"],
  },
  {
    id: "sapphire-drift",
    name: "Sapphire Drift",
    colors: ["#0c1231", "#1b2764", "#364cb9", "#939fdd", "#dadef2"],
    category: "Warm",
    style: "Earthy",
    tags: ["elegant", "calm"],
  },
  {
    id: "clay-storm",
    name: "Clay Storm",
    colors: ["#3b1423", "#681d27", "#ce4330", "#e0b094", "#f0e5d4"],
    category: "Urban",
    style: "Earthy",
    tags: ["energetic", "bold"],
  },
  {
    id: "saffron-trail",
    name: "Saffron Trail",
    colors: ["#453108", "#8e6514", "#d09622", "#e7c47f", "#f4e7cd"],
    category: "Nature",
    style: "Dark",
    tags: ["bold", "moody"],
  },
  {
    id: "mustard-veil",
    name: "Mustard Veil",
    colors: ["#2e2813", "#6f692f", "#a1a647", "#c5d092", "#ebf1de"],
    category: "Abstract",
    style: "Earthy",
    tags: ["serene", "elegant"],
  },
  {
    id: "fern-ember",
    name: "Fern Ember",
    colors: ["#3c3908", "#798113", "#aacd1e", "#c3ea74", "#eaf9d8"],
    category: "Cool",
    style: "Warm",
    tags: ["moody", "elegant"],
  },
  {
    id: "blush-peak",
    name: "Blush Peak",
    colors: ["#430835", "#6f1059", "#d323aa", "#e576cb", "#f8e1f3"],
    category: "Nature",
    style: "Dark",
    tags: ["calm", "vibrant"],
  },
  {
    id: "punch-frost",
    name: "Punch Frost",
    colors: ["#390626", "#820e47", "#e62268", "#ef748f", "#fbdbde"],
    category: "Abstract",
    style: "Neon",
    tags: ["cozy", "energetic"],
  },
  {
    id: "berry-trail",
    name: "Berry Trail",
    colors: ["#310d36", "#731f7d", "#bc34cc", "#91e188", "#cff2cb"],
    category: "Urban",
    style: "Warm",
    tags: ["energetic", "serene"],
  },
  {
    id: "rust-wave",
    name: "Rust Wave",
    colors: ["#231016", "#5d262a", "#b85743", "#d2ae92", "#f2ede4"],
    category: "Nature",
    style: "Warm",
    tags: ["calm", "elegant"],
  },
  {
    id: "sapphire-bloom",
    name: "Sapphire Bloom",
    colors: ["#0c1630", "#1d3775", "#315bc3", "#dcc079", "#f1e6cb"],
    category: "Vintage",
    style: "Dark",
    tags: ["cozy", "bold"],
  },
  {
    id: "moss-peak",
    name: "Moss Peak",
    colors: ["#243009", "#567017", "#8fba2a", "#c7e28a", "#ebf4d6"],
    category: "Nature",
    style: "Warm",
    tags: ["bold", "calm"],
  },
  {
    id: "salmon-shore",
    name: "Salmon Shore",
    colors: ["#2a0414", "#720f39", "#de2775", "#e87daa", "#f6d1e0"],
    category: "Vintage",
    style: "Neon",
    tags: ["cozy", "fresh"],
  },
  {
    id: "cobalt-ember",
    name: "Cobalt Ember",
    colors: ["#131a2a", "#34436b", "#546ba7", "#a2afcf", "#e0e4ee"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "lemon-veil",
    name: "Lemon Veil",
    colors: ["#3a4107", "#778311", "#c2d520", "#dbe777", "#eef3c4"],
    category: "Cool",
    style: "Neon",
    tags: ["playful", "elegant"],
  },
  {
    id: "lemon-echo",
    name: "Lemon Echo",
    colors: ["#271c04", "#846d0e", "#ded118", "#e6ef6b", "#ecf8be"],
    category: "Abstract",
    style: "Neon",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "mauve-wave",
    name: "Mauve Wave",
    colors: ["#310b24", "#841e62", "#ca2d96", "#8be4a8", "#d2f4dd"],
    category: "Vintage",
    style: "Dark",
    tags: ["fresh", "bold"],
  },
  {
    id: "olive-dream",
    name: "Olive Dream",
    colors: ["#3a2e0e", "#7b7818", "#b1db20", "#ace270", "#dbf3d2"],
    category: "Urban",
    style: "Vibrant",
    tags: ["moody", "playful"],
  },
  {
    id: "mint-storm",
    name: "Mint Storm",
    colors: ["#0c3a2f", "#1d826a", "#2fc19e", "#8be0cb", "#d0f1e9"],
    category: "Urban",
    style: "Vibrant",
    tags: ["moody", "serene"],
  },
  {
    id: "orchid-dawn",
    name: "Orchid Dawn",
    colors: ["#330735", "#7b1581", "#c827d2", "#e086e6", "#f2d0f4"],
    category: "Nature",
    style: "Earthy",
    tags: ["cozy", "playful"],
  },
  {
    id: "sapphire-shore",
    name: "Sapphire Shore",
    colors: ["#0d2539", "#183764", "#2c52b7", "#7c8adf", "#e0e0f7"],
    category: "Warm",
    style: "Cool",
    tags: ["cozy", "bold"],
  },
  {
    id: "steel-echo",
    name: "Steel Echo",
    colors: ["#11172c", "#283768", "#445db0", "#d2c28c", "#ece5cf"],
    category: "Abstract",
    style: "Cool",
    tags: ["serene", "cozy"],
  },
  {
    id: "salmon-harbor",
    name: "Salmon Harbor",
    colors: ["#450a2e", "#791343", "#d2205c", "#ea7d94", "#f5c2c5"],
    category: "Nature",
    style: "Dark",
    tags: ["playful", "bold"],
  },
  {
    id: "navy-peak",
    name: "Navy Peak",
    colors: ["#0c072b", "#201570", "#3d2ac6", "#958be3", "#d5d1f3"],
    category: "Cool",
    style: "Earthy",
    tags: ["elegant", "serene"],
  },
  {
    id: "mint-dawn",
    name: "Mint Dawn",
    colors: ["#092717", "#1e7956", "#37cca7", "#7bddd2", "#ccf1f2"],
    category: "Urban",
    style: "Cool",
    tags: ["fresh", "serene"],
  },
  {
    id: "plum-peak",
    name: "Plum Peak",
    colors: ["#240631", "#571176", "#a529db", "#cc8be9", "#edd7f6"],
    category: "Abstract",
    style: "Neon",
    tags: ["cozy", "playful"],
  },
  {
    id: "citrus-echo",
    name: "Citrus Echo",
    colors: ["#2e1b10", "#6d5121", "#bfae31", "#d2dc8f", "#e2eecf"],
    category: "Warm",
    style: "Warm",
    tags: ["calm", "serene"],
  },
  {
    id: "flamingo-trail",
    name: "Flamingo Trail",
    colors: ["#2a0817", "#771842", "#c1286b", "#7fe4b8", "#d8f7e9"],
    category: "Cool",
    style: "Warm",
    tags: ["bold", "playful"],
  },
  {
    id: "steel-whisper",
    name: "Steel Whisper",
    colors: ["#0e2c42", "#1b457a", "#3062d1", "#8999e4", "#dfe0f7"],
    category: "Urban",
    style: "Warm",
    tags: ["energetic", "serene"],
  },
  {
    id: "olive-storm",
    name: "Olive Storm",
    colors: ["#424505", "#6e840a", "#a7ea13", "#bef47c", "#ddfac8"],
    category: "Cool",
    style: "Neon",
    tags: ["fresh", "energetic"],
  },
  {
    id: "jungle-grove",
    name: "Jungle Grove",
    colors: ["#0b2a25", "#1e6a5d", "#39bda6", "#98ddd1", "#d1efea"],
    category: "Nature",
    style: "Dark",
    tags: ["elegant", "bold"],
  },
  {
    id: "sage-veil",
    name: "Sage Veil",
    colors: ["#1f270c", "#506420", "#97bd3d", "#9c84d7", "#ded6f1"],
    category: "Vintage",
    style: "Cool",
    tags: ["serene", "vibrant"],
  },
  {
    id: "olive-whisper",
    name: "Olive Whisper",
    colors: ["#1e230e", "#4f5c27", "#97af4e", "#c4d19d", "#e5ead4"],
    category: "Nature",
    style: "Vibrant",
    tags: ["moody", "vibrant"],
  },
  {
    id: "sapphire-whisper",
    name: "Sapphire Whisper",
    colors: ["#131a2e", "#263257", "#556bb1", "#94a1cc", "#d5daea"],
    category: "Vintage",
    style: "Warm",
    tags: ["energetic", "serene"],
  },
  {
    id: "brick-frost",
    name: "Brick Frost",
    colors: ["#351406", "#8c3511", "#e45b22", "#78cbee", "#c4e8f7"],
    category: "Abstract",
    style: "Neon",
    tags: ["serene", "moody"],
  },
  {
    id: "rosewood-ember",
    name: "Rosewood Ember",
    colors: ["#270a1f", "#64194f", "#bc3094", "#82de9c", "#cbf1d6"],
    category: "Abstract",
    style: "Dark",
    tags: ["energetic", "elegant"],
  },
  {
    id: "spruce-storm",
    name: "Spruce Storm",
    colors: ["#112809", "#146a13", "#1ddc4b", "#7ee7b2", "#dff7f1"],
    category: "Warm",
    style: "Vibrant",
    tags: ["vibrant", "cozy"],
  },
  {
    id: "bronze-glow",
    name: "Bronze Glow",
    colors: ["#291b11", "#624129", "#b1754b", "#93b7d1", "#d6e3ed"],
    category: "Urban",
    style: "Vibrant",
    tags: ["fresh", "cozy"],
  },
  {
    id: "violet-canyon",
    name: "Violet Canyon",
    colors: ["#0e0c1c", "#35275b", "#6e49a8", "#b99cd4", "#e8dbef"],
    category: "Warm",
    style: "Vibrant",
    tags: ["fresh", "energetic"],
  },
  {
    id: "gold-trail",
    name: "Gold Trail",
    colors: ["#36210e", "#6b4d1b", "#bc9a31", "#e0d689", "#eff0c7"],
    category: "Warm",
    style: "Vibrant",
    tags: ["moody", "cozy"],
  },
  {
    id: "terracotta-trail",
    name: "Terracotta Trail",
    colors: ["#2e0704", "#80240b", "#ce5312", "#f3b67d", "#fbebd3"],
    category: "Nature",
    style: "Neon",
    tags: ["calm", "moody"],
  },
  {
    id: "bronze-bay",
    name: "Bronze Bay",
    colors: ["#2b1617", "#6c3e33", "#b47e54", "#cfbe9a", "#e7e5d1"],
    category: "Urban",
    style: "Vibrant",
    tags: ["moody", "bold"],
  },
  {
    id: "sky-bay",
    name: "Sky Bay",
    colors: ["#081e20", "#185371", "#2370d9", "#788ae2", "#cbc8f0"],
    category: "Abstract",
    style: "Cool",
    tags: ["moody", "bold"],
  },
  {
    id: "azure-dusk",
    name: "Azure Dusk",
    colors: ["#163332", "#2c6472", "#3f81b7", "#849acf", "#d1d2eb"],
    category: "Abstract",
    style: "Cool",
    tags: ["elegant", "moody"],
  },
  {
    id: "fuchsia-valley",
    name: "Fuchsia Valley",
    colors: ["#2b063b", "#680e7a", "#d91adf", "#ee6fe1", "#f7c1eb"],
    category: "Urban",
    style: "Vibrant",
    tags: ["vibrant", "moody"],
  },
  {
    id: "aqua-dawn",
    name: "Aqua Dawn",
    colors: ["#12282b", "#255157", "#4ea8b4", "#cd9188", "#f4e7e5"],
    category: "Urban",
    style: "Warm",
    tags: ["fresh", "calm"],
  },
  {
    id: "terracotta-storm",
    name: "Terracotta Storm",
    colors: ["#391c0d", "#7e3e1e", "#b75a2b", "#7abddf", "#d6eaf5"],
    category: "Urban",
    style: "Dark",
    tags: ["vibrant", "playful"],
  },
  {
    id: "marine-echo",
    name: "Marine Echo",
    colors: ["#0d4039", "#13707d", "#209de8", "#86acec", "#d1d6f5"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["bold", "vibrant"],
  },
  {
    id: "rosewood-mist",
    name: "Rosewood Mist",
    colors: ["#2d0d1f", "#7b2555", "#ab3476", "#7bd6a4", "#d1f0df"],
    category: "Urban",
    style: "Dark",
    tags: ["cozy", "calm"],
  },
  {
    id: "clover-glow",
    name: "Clover Glow",
    colors: ["#18440a", "#318516", "#56d72e", "#98e480", "#dff5d7"],
    category: "Nature",
    style: "Vibrant",
    tags: ["moody", "elegant"],
  },
  {
    id: "fern-haze",
    name: "Fern Haze",
    colors: ["#133626", "#215c48", "#40b099", "#9bdad6", "#e0f2f3"],
    category: "Urban",
    style: "Warm",
    tags: ["moody", "fresh"],
  },
  {
    id: "flamingo-frost",
    name: "Flamingo Frost",
    colors: ["#310515", "#8c113e", "#d31e60", "#ec8aae", "#f4c6d7"],
    category: "Vintage",
    style: "Neon",
    tags: ["playful", "calm"],
  },
  {
    id: "brick-glow",
    name: "Brick Glow",
    colors: ["#341013", "#61231f", "#be573d", "#deb19a", "#f7eee6"],
    category: "Urban",
    style: "Vibrant",
    tags: ["playful", "cozy"],
  },
  {
    id: "citrus-ember",
    name: "Citrus Ember",
    colors: ["#20140a", "#6d551d", "#bab429", "#ccde86", "#ebf5e0"],
    category: "Urban",
    style: "Dark",
    tags: ["moody", "vibrant"],
  },
  {
    id: "denim-trail",
    name: "Denim Trail",
    colors: ["#0f2742", "#1a3975", "#2b4abf", "#7a82e0", "#d5d3f5"],
    category: "Nature",
    style: "Vibrant",
    tags: ["playful", "serene"],
  },
  {
    id: "meadow-drift",
    name: "Meadow Drift",
    colors: ["#132906", "#387414", "#6cd62b", "#ade68a", "#e4f6d9"],
    category: "Urban",
    style: "Earthy",
    tags: ["elegant", "energetic"],
  },
  {
    id: "terracotta-bay",
    name: "Terracotta Bay",
    colors: ["#42080c", "#6d110d", "#e13f1b", "#ec9268", "#f9e2cf"],
    category: "Urban",
    style: "Dark",
    tags: ["vibrant", "bold"],
  },
  {
    id: "mint-harbor",
    name: "Mint Harbor",
    colors: ["#142e27", "#2f6656", "#56ae95", "#94cabb", "#d2e8e2"],
    category: "Urban",
    style: "Warm",
    tags: ["playful", "vibrant"],
  },
  {
    id: "orchid-trail",
    name: "Orchid Trail",
    colors: ["#25112c", "#562864", "#9d50b5", "#ba86ca", "#e6d4eb"],
    category: "Cool",
    style: "Cool",
    tags: ["playful", "energetic"],
  },
  {
    id: "sky-harbor",
    name: "Sky Harbor",
    colors: ["#15293b", "#254a68", "#4585bb", "#d7b292", "#f5ece4"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["cozy", "bold"],
  },
  {
    id: "steel-bay",
    name: "Steel Bay",
    colors: ["#081235", "#172c7e", "#2f51d4", "#889be4", "#d3daf4"],
    category: "Warm",
    style: "Warm",
    tags: ["serene", "elegant"],
  },
  {
    id: "mustard-dream",
    name: "Mustard Dream",
    colors: ["#38290c", "#6b5917", "#bcb129", "#dfe487", "#f4f8e2"],
    category: "Urban",
    style: "Warm",
    tags: ["serene", "energetic"],
  },
  {
    id: "peony-drift",
    name: "Peony Drift",
    colors: ["#36142a", "#5b2448", "#9e427f", "#ce8fb8", "#f5e9f1"],
    category: "Cool",
    style: "Cool",
    tags: ["cozy", "energetic"],
  },
  {
    id: "mustard-bloom",
    name: "Mustard Bloom",
    colors: ["#36320b", "#797119", "#c1b428", "#707ae1", "#c6caf3"],
    category: "Abstract",
    style: "Earthy",
    tags: ["serene", "moody"],
  },
  {
    id: "steel-valley",
    name: "Steel Valley",
    colors: ["#0e1923", "#273e63", "#4e69b9", "#9da4d8", "#e7e7f5"],
    category: "Urban",
    style: "Earthy",
    tags: ["fresh", "energetic"],
  },
  {
    id: "grape-haze",
    name: "Grape Haze",
    colors: ["#120a2f", "#491684", "#a719df", "#e787eb", "#f7dcf1"],
    category: "Abstract",
    style: "Neon",
    tags: ["fresh", "moody"],
  },
  {
    id: "olive-frost",
    name: "Olive Frost",
    colors: ["#252704", "#65790e", "#a0e01a", "#bcef7d", "#daf8c5"],
    category: "Nature",
    style: "Neon",
    tags: ["moody", "elegant"],
  },
  {
    id: "amethyst-peak",
    name: "Amethyst Peak",
    colors: ["#0d0d20", "#2e265c", "#6649af", "#a78cce", "#e5d9ef"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["moody", "bold"],
  },
  {
    id: "lavender-haze",
    name: "Lavender Haze",
    colors: ["#19162a", "#3d2a59", "#8a4bab", "#c99ace", "#eedfeb"],
    category: "Urban",
    style: "Vibrant",
    tags: ["energetic", "calm"],
  },
  {
    id: "lemon-dream",
    name: "Lemon Dream",
    colors: ["#1f210a", "#59601e", "#b7c345", "#8880d6", "#d4d1f0"],
    category: "Cool",
    style: "Earthy",
    tags: ["serene", "elegant"],
  },
  {
    id: "lagoon-wave",
    name: "Lagoon Wave",
    colors: ["#0e3929", "#188476", "#1bb3c7", "#7dbfe6", "#c9d8f1"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["playful", "vibrant"],
  },
  {
    id: "basil-frost",
    name: "Basil Frost",
    colors: ["#1e420e", "#36741b", "#57b52e", "#a7df8e", "#e2f4db"],
    category: "Cool",
    style: "Cool",
    tags: ["serene", "elegant"],
  },
  {
    id: "coral-drift",
    name: "Coral Drift",
    colors: ["#3b0610", "#810d24", "#e61741", "#74f0d7", "#dcfbf5"],
    category: "Vintage",
    style: "Neon",
    tags: ["cozy", "bold"],
  },
  {
    id: "aqua-haze",
    name: "Aqua Haze",
    colors: ["#062327", "#126a75", "#20bcd0", "#ea897c", "#fae5e3"],
    category: "Warm",
    style: "Earthy",
    tags: ["elegant", "moody"],
  },
  {
    id: "lemon-storm",
    name: "Lemon Storm",
    colors: ["#331f0b", "#745b13", "#e5e41b", "#cde878", "#eaf7dd"],
    category: "Abstract",
    style: "Vibrant",
    tags: ["elegant", "vibrant"],
  },
  {
    id: "flamingo-wave",
    name: "Flamingo Wave",
    colors: ["#200e13", "#6c3041", "#a44963", "#91cebd", "#dcefea"],
    category: "Urban",
    style: "Warm",
    tags: ["serene", "fresh"],
  },
  {
    id: "ocean-shore",
    name: "Ocean Shore",
    colors: ["#0d222f", "#1d4a66", "#3588bd", "#e1b396", "#f1dbce"],
    category: "Warm",
    style: "Vibrant",
    tags: ["calm", "bold"],
  },
  {
    id: "magenta-shore",
    name: "Magenta Shore",
    colors: ["#130826", "#501275", "#c318dc", "#eb88df", "#f4cee6"],
    category: "Abstract",
    style: "Neon",
    tags: ["energetic", "bold"],
  },
  {
    id: "denim-dusk",
    name: "Denim Dusk",
    colors: ["#191e35", "#313b64", "#5363a4", "#8f99c4", "#dce0ec"],
    category: "Abstract",
    style: "Dark",
    tags: ["cozy", "calm"],
  },
  {
    id: "meadow-storm",
    name: "Meadow Storm",
    colors: ["#232e0f", "#4e7226", "#6fbb3f", "#99d585", "#d2eece"],
    category: "Abstract",
    style: "Dark",
    tags: ["vibrant", "serene"],
  },
  {
    id: "mauve-dawn",
    name: "Mauve Dawn",
    colors: ["#3a142f", "#73275d", "#b83f94", "#83d49b", "#d3efdb"],
    category: "Nature",
    style: "Warm",
    tags: ["energetic", "calm"],
  },
  {
    id: "punch-bloom",
    name: "Punch Bloom",
    colors: ["#231222", "#652f54", "#b24d78", "#cd96a0", "#f3eae9"],
    category: "Abstract",
    style: "Dark",
    tags: ["cozy", "elegant"],
  },
  {
    id: "ocean-harbor",
    name: "Ocean Harbor",
    colors: ["#081721", "#1e4e6f", "#3283bc", "#dea985", "#f1dbcc"],
    category: "Abstract",
    style: "Earthy",
    tags: ["fresh", "playful"],
  },
  {
    id: "mauve-peak",
    name: "Mauve Peak",
    colors: ["#2e0a21", "#701a50", "#c92f90", "#84e2a7", "#e5f8ec"],
    category: "Urban",
    style: "Cool",
    tags: ["serene", "playful"],
  },
  {
    id: "marine-grove",
    name: "Marine Grove",
    colors: ["#132e30", "#2a5f6d", "#478fb6", "#9abad7", "#cfdaec"],
    category: "Abstract",
    style: "Cool",
    tags: ["fresh", "moody"],
  },
  {
    id: "blush-valley",
    name: "Blush Valley",
    colors: ["#29162e", "#5e285d", "#b34494", "#d69fb9", "#ecd6db"],
    category: "Vintage",
    style: "Warm",
    tags: ["elegant", "fresh"],
  },
  {
    id: "berry-wave",
    name: "Berry Wave",
    colors: ["#1c0426", "#79118d", "#de24e3", "#eb65dd", "#f9d3f0"],
    category: "Warm",
    style: "Neon",
    tags: ["calm", "bold"],
  },
  {
    id: "salmon-glow",
    name: "Salmon Glow",
    colors: ["#300817", "#771438", "#c6225d", "#71e6bc", "#c6f5e4"],
    category: "Cool",
    style: "Cool",
    tags: ["energetic", "cozy"],
  },
  {
    id: "ruby-shore",
    name: "Ruby Shore",
    colors: ["#361619", "#682c33", "#b4545f", "#ca8b92", "#e9d2d4"],
    category: "Vintage",
    style: "Warm",
    tags: ["serene", "playful"],
  },
  {
    id: "magenta-haze",
    name: "Magenta Haze",
    colors: ["#180e23", "#552367", "#aa33ad", "#d78dc6", "#f3e1ea"],
    category: "Cool",
    style: "Cool",
    tags: ["vibrant", "elegant"],
  },
  {
    id: "coral-mist",
    name: "Coral Mist",
    colors: ["#2a111a", "#692c41", "#a14463", "#9ad4c0", "#e9f5f1"],
    category: "Cool",
    style: "Cool",
    tags: ["vibrant", "fresh"],
  },
  {
    id: "lavender-veil",
    name: "Lavender Veil",
    colors: ["#280935", "#5c1879", "#9c2ccc", "#cb90e4", "#ecd7f4"],
    category: "Cool",
    style: "Dark",
    tags: ["vibrant", "moody"],
  },
  {
    id: "azure-dawn",
    name: "Azure Dawn",
    colors: ["#0a121f", "#284677", "#406fbe", "#dabf93", "#f2e9da"],
    category: "Cool",
    style: "Dark",
    tags: ["serene", "energetic"],
  },
  {
    id: "lagoon-dawn",
    name: "Lagoon Dawn",
    colors: ["#0b1b20", "#255869", "#489eba", "#8abfd1", "#d0e4eb"],
    category: "Nature",
    style: "Cool",
    tags: ["fresh", "energetic"],
  },
  {
    id: "iris-veil",
    name: "Iris Veil",
    colors: ["#131233", "#302469", "#6843bd", "#b598db", "#e4d4f0"],
    category: "Urban",
    style: "Dark",
    tags: ["serene", "energetic"],
  },
  {
    id: "steel-grove",
    name: "Steel Grove",
    colors: ["#0a2025", "#1a4f77", "#2761da", "#727ae0", "#d5cff1"],
    category: "Urban",
    style: "Vibrant",
    tags: ["moody", "playful"],
  },
  {
    id: "olive-valley",
    name: "Olive Valley",
    colors: ["#303f0b", "#4f6614", "#91ba29", "#c0dd76", "#ebf3d4"],
    category: "Warm",
    style: "Cool",
    tags: ["bold", "calm"],
  },
  {
    id: "bronze-shore",
    name: "Bronze Shore",
    colors: ["#3c0c05", "#8a2c0d", "#d15c14", "#f2bb80", "#f9e6c2"],
    category: "Nature",
    style: "Neon",
    tags: ["energetic", "cozy"],
  },
  {
    id: "rust-frost",
    name: "Rust Frost",
    colors: ["#240905", "#7c2012", "#da3a20", "#68d6e8", "#c2eef5"],
    category: "Vintage",
    style: "Earthy",
    tags: ["elegant", "playful"],
  },
  {
    id: "lavender-harbor",
    name: "Lavender Harbor",
    colors: ["#150d3a", "#431782", "#991cda", "#d96ce4", "#f8e4f5"],
    category: "Nature",
    style: "Vibrant",
    tags: ["serene", "vibrant"],
  },
  {
    id: "rust-haze",
    name: "Rust Haze",
    colors: ["#250c05", "#6e2310", "#de4922", "#7fd5ec", "#d1f0f8"],
    category: "Vintage",
    style: "Earthy",
    tags: ["serene", "bold"],
  },
  {
    id: "citrus-peak",
    name: "Citrus Peak",
    colors: ["#3e3d10", "#61601b", "#c3c239", "#d6d67f", "#eeeece"],
    category: "Warm",
    style: "Dark",
    tags: ["fresh", "moody"],
  },
  {
    id: "copper-harbor",
    name: "Copper Harbor",
    colors: ["#2d2213", "#664e2c", "#9c7846", "#cab18e", "#ece3d8"],
    category: "Warm",
    style: "Warm",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "clover-whisper",
    name: "Clover Whisper",
    colors: ["#17220b", "#39611e", "#5bb73a", "#9adc90", "#d9f3da"],
    category: "Urban",
    style: "Vibrant",
    tags: ["fresh", "playful"],
  },
  {
    id: "grape-veil",
    name: "Grape Veil",
    colors: ["#170c1f", "#4d2a6a", "#874fb5", "#b492cf", "#ece4f2"],
    category: "Urban",
    style: "Earthy",
    tags: ["energetic", "cozy"],
  },
  {
    id: "emerald-valley",
    name: "Emerald Valley",
    colors: ["#0c3920", "#1b7745", "#2db66b", "#90e1b5", "#d1f1df"],
    category: "Urban",
    style: "Earthy",
    tags: ["fresh", "vibrant"],
  },
  {
    id: "azure-haze",
    name: "Azure Haze",
    colors: ["#0d2734", "#1b4467", "#2f64b3", "#7993db", "#cbd0f1"],
    category: "Cool",
    style: "Warm",
    tags: ["energetic", "serene"],
  },
  {
    id: "emerald-ember",
    name: "Emerald Ember",
    colors: ["#0f371f", "#237c45", "#33b666", "#d97bb4", "#f1cee3"],
    category: "Urban",
    style: "Warm",
    tags: ["playful", "bold"],
  },
  {
    id: "coral-wave",
    name: "Coral Wave",
    colors: ["#341a30", "#612b4b", "#aa4567", "#ca8b90", "#f1e5e2"],
    category: "Urban",
    style: "Cool",
    tags: ["elegant", "energetic"],
  },
  {
    id: "coral-veil",
    name: "Coral Veil",
    colors: ["#2a1123", "#62294a", "#b34c7a", "#ce8ba0", "#edd5d9"],
    category: "Abstract",
    style: "Earthy",
    tags: ["vibrant", "bold"],
  },
  {
    id: "berry-haze",
    name: "Berry Haze",
    colors: ["#300d3d", "#62176e", "#d02dd1", "#e589d9", "#f4cce9"],
    category: "Abstract",
    style: "Earthy",
    tags: ["energetic", "calm"],
  },
  {
    id: "grape-frost",
    name: "Grape Frost",
    colors: ["#22093e", "#4d1274", "#ac28dc", "#da7bea", "#f7d0f7"],
    category: "Warm",
    style: "Dark",
    tags: ["elegant", "moody"],
  },
  {
    id: "magenta-echo",
    name: "Magenta Echo",
    colors: ["#250e35", "#661a75", "#c922ba", "#e385c4", "#f6e0e9"],
    category: "Urban",
    style: "Vibrant",
    tags: ["moody", "fresh"],
  },
  {
    id: "sage-trail",
    name: "Sage Trail",
    colors: ["#1e240f", "#58682e", "#8ea84c", "#c5d2a1", "#e9eedd"],
    category: "Cool",
    style: "Cool",
    tags: ["vibrant", "energetic"],
  },
  {
    id: "cosmos-shore",
    name: "Cosmos Shore",
    colors: ["#0a0b20", "#292a74", "#3f40aa", "#9d9ed9", "#dedff1"],
    category: "Vintage",
    style: "Cool",
    tags: ["elegant", "moody"],
  },
  {
    id: "lake-bloom",
    name: "Lake Bloom",
    colors: ["#0e2024", "#285a66", "#4ea5b9", "#d6a499", "#ebd2cd"],
    category: "Urban",
    style: "Warm",
    tags: ["serene", "energetic"],
  },
  {
    id: "moss-trail",
    name: "Moss Trail",
    colors: ["#1d200c", "#60742e", "#84b146", "#add28f", "#deeed6"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["elegant", "serene"],
  },
  {
    id: "twilight-dusk",
    name: "Twilight Dusk",
    colors: ["#0a0824", "#271763", "#6b36cf", "#b58ce3", "#f0e4f8"],
    category: "Nature",
    style: "Earthy",
    tags: ["vibrant", "serene"],
  },
  {
    id: "teal-glow",
    name: "Teal Glow",
    colors: ["#053841", "#0d7f95", "#14c5e6", "#f3907d", "#fbded8"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["fresh", "moody"],
  },
  {
    id: "blush-bay",
    name: "Blush Bay",
    colors: ["#3a1030", "#6b215a", "#ac3791", "#d37fbf", "#f2ddee"],
    category: "Warm",
    style: "Earthy",
    tags: ["bold", "calm"],
  },
  {
    id: "iris-trail",
    name: "Iris Trail",
    colors: ["#160434", "#390d80", "#651cdd", "#a57aeb", "#d6c3f5"],
    category: "Urban",
    style: "Vibrant",
    tags: ["playful", "elegant"],
  },
  {
    id: "wine-glow",
    name: "Wine Glow",
    colors: ["#2c0e10", "#6d2428", "#af3940", "#97dcd9", "#e0f4f3"],
    category: "Warm",
    style: "Warm",
    tags: ["energetic", "playful"],
  },
  {
    id: "blush-whisper",
    name: "Blush Whisper",
    colors: ["#361434", "#612455", "#b1438d", "#d899bb", "#eed4df"],
    category: "Abstract",
    style: "Warm",
    tags: ["moody", "bold"],
  },
  {
    id: "mustard-peak",
    name: "Mustard Peak",
    colors: ["#2d2016", "#5b4c2a", "#a39d44", "#cad4a1", "#e9efe1"],
    category: "Warm",
    style: "Dark",
    tags: ["moody", "fresh"],
  },
  {
    id: "lavender-shore",
    name: "Lavender Shore",
    colors: ["#250a32", "#5d197d", "#8e26be", "#a0e580", "#e1f6d7"],
    category: "Abstract",
    style: "Earthy",
    tags: ["calm", "energetic"],
  },
  {
    id: "citrus-bay",
    name: "Citrus Bay",
    colors: ["#2b290e", "#75722a", "#ada941", "#d1ce8b", "#f0efdb"],
    category: "Vintage",
    style: "Earthy",
    tags: ["energetic", "fresh"],
  },
  {
    id: "tide-harbor",
    name: "Tide Harbor",
    colors: ["#112433", "#234965", "#3f83b6", "#d6aa88", "#eedcce"],
    category: "Warm",
    style: "Dark",
    tags: ["elegant", "moody"],
  },
  {
    id: "olive-glow",
    name: "Olive Glow",
    colors: ["#3b3a0e", "#737c1e", "#a4c531", "#c2e28a", "#eef8e4"],
    category: "Cool",
    style: "Vibrant",
    tags: ["moody", "fresh"],
  },
  {
    id: "ruby-wave",
    name: "Ruby Wave",
    colors: ["#270707", "#771515", "#d92f2f", "#7ee7e7", "#e4fafa"],
    category: "Nature",
    style: "Cool",
    tags: ["fresh", "bold"],
  },
  {
    id: "lemon-dawn",
    name: "Lemon Dawn",
    colors: ["#1f200d", "#565824", "#adb24a", "#9e9bd5", "#d0ceea"],
    category: "Nature",
    style: "Warm",
    tags: ["bold", "fresh"],
  },
  {
    id: "orchid-whisper",
    name: "Orchid Whisper",
    colors: ["#191121", "#4b2755", "#b14aae", "#d19dc3", "#f1e4ea"],
    category: "Abstract",
    style: "Earthy",
    tags: ["bold", "energetic"],
  },
  {
    id: "copper-wave",
    name: "Copper Wave",
    colors: ["#321704", "#75360b", "#df6715", "#7bc2f2", "#c6e5f9"],
    category: "Abstract",
    style: "Neon",
    tags: ["calm", "vibrant"],
  },
  {
    id: "pine-dawn",
    name: "Pine Dawn",
    colors: ["#1e3806", "#3c9110", "#3dcd16", "#74ee6a", "#d1f9d3"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["serene", "energetic"],
  },
  {
    id: "honey-dream",
    name: "Honey Dream",
    colors: ["#352504", "#835b0b", "#dd9913", "#7ca4f3", "#c9d9fa"],
    category: "Cool",
    style: "Neon",
    tags: ["elegant", "cozy"],
  },
  {
    id: "reef-bloom",
    name: "Reef Bloom",
    colors: ["#132d29", "#255c61", "#4798c0", "#8eabd3", "#dce0f0"],
    category: "Urban",
    style: "Warm",
    tags: ["fresh", "moody"],
  },
  {
    id: "rose-storm",
    name: "Rose Storm",
    colors: ["#2c0c18", "#741b25", "#d43e27", "#de9e76", "#f2e7d4"],
    category: "Vintage",
    style: "Vibrant",
    tags: ["energetic", "fresh"],
  },
  {
    id: "tide-frost",
    name: "Tide Frost",
    colors: ["#19312b", "#2f6768", "#458da6", "#9cb6d1", "#dfe3ef"],
    category: "Warm",
    style: "Warm",
    tags: ["moody", "playful"],
  },
  {
    id: "jungle-echo",
    name: "Jungle Echo",
    colors: ["#112115", "#2d6146", "#4aaf95", "#8cc9c8", "#d2e3e8"],
    category: "Nature",
    style: "Dark",
    tags: ["moody", "calm"],
  },
  {
    id: "ocean-haze",
    name: "Ocean Haze",
    colors: ["#092e3a", "#15617a", "#27a5cc", "#7fcbe3", "#ceeaf3"],
    category: "Abstract",
    style: "Cool",
    tags: ["elegant", "vibrant"],
  },
  {
    id: "cosmos-glow",
    name: "Cosmos Glow",
    colors: ["#0f0c29", "#282068", "#483cb6", "#877fd2", "#dddbf1"],
    category: "Vintage",
    style: "Cool",
    tags: ["energetic", "moody"],
  },
];

export default palettes;
